using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SistemaLlantas.Domain.Entities;

namespace SistemaLlantas.Infrastructure.Persistence;

public sealed class FlujosConfiguration:IEntityTypeConfiguration<SolicitudOperacion>,IEntityTypeConfiguration<ProveedorServicio>,IEntityTypeConfiguration<OrdenServicioLlanta>,IEntityTypeConfiguration<EvidenciaFlujo>,IEntityTypeConfiguration<CargaMasiva>
{
 public void Configure(EntityTypeBuilder<SolicitudOperacion> b){Base(b,"SolicitudOperacion");b.Property(x=>x.Tipo).HasMaxLength(50);b.Property(x=>x.TipoDestino).HasMaxLength(50);b.Property(x=>x.Motivo).HasMaxLength(500);b.Property(x=>x.Observaciones).HasMaxLength(1000);b.Property(x=>x.Solicitante).HasMaxLength(150);b.Property(x=>x.Aprobador).HasMaxLength(150);b.Property(x=>x.MotivoRechazo).HasMaxLength(500);b.Property(x=>x.KilometrajeVehiculo).HasPrecision(18,2);b.HasIndex(x=>new{x.CentroId,x.Estado,x.FechaCreacion});b.HasOne(x=>x.Centro).WithMany().HasForeignKey(x=>x.CentroId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.Llanta).WithMany().HasForeignKey(x=>x.LlantaId).OnDelete(DeleteBehavior.Restrict);}
 public void Configure(EntityTypeBuilder<ProveedorServicio> b){Base(b,"ProveedorServicio");b.Property(x=>x.Codigo).HasMaxLength(30);b.Property(x=>x.Nombre).HasMaxLength(150);b.Property(x=>x.Tipo).HasMaxLength(30);b.HasIndex(x=>x.Codigo).IsUnique();}
 public void Configure(EntityTypeBuilder<OrdenServicioLlanta> b){Base(b,"OrdenServicioLlanta");b.Property(x=>x.Estado).HasMaxLength(40);b.Property(x=>x.Costo).HasPrecision(18,2);b.Property(x=>x.Motivo).HasMaxLength(500);b.Property(x=>x.Observaciones).HasMaxLength(1000);b.Property(x=>x.CriterioElegibilidad).HasMaxLength(500);b.Property(x=>x.Solicitante).HasMaxLength(150);b.Property(x=>x.Aprobador).HasMaxLength(150);b.HasIndex(x=>new{x.Tipo,x.Estado,x.CentroOrigenId});b.HasOne(x=>x.Llanta).WithMany().HasForeignKey(x=>x.LlantaId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.CentroOrigen).WithMany().HasForeignKey(x=>x.CentroOrigenId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.Proveedor).WithMany().HasForeignKey(x=>x.ProveedorId).OnDelete(DeleteBehavior.Restrict);}
 public void Configure(EntityTypeBuilder<EvidenciaFlujo> b){Base(b,"EvidenciaFlujo");b.Property(x=>x.NombreArchivo).HasMaxLength(255);b.Property(x=>x.Ubicacion).HasMaxLength(1000);b.Property(x=>x.MimeType).HasMaxLength(100);b.Property(x=>x.Hash).HasMaxLength(128);b.HasOne(x=>x.Orden).WithMany(x=>x.Evidencias).HasForeignKey(x=>x.OrdenServicioLlantaId);}
 public void Configure(EntityTypeBuilder<CargaMasiva> b){Base(b,"CargaMasiva");b.Property(x=>x.Tipo).HasMaxLength(30);b.Property(x=>x.NombreArchivo).HasMaxLength(255);b.Property(x=>x.Estado).HasMaxLength(30);b.Property(x=>x.Usuario).HasMaxLength(150);b.HasIndex(x=>new{x.Usuario,x.FechaCreacion});}
 private static void Base<T>(EntityTypeBuilder<T> b,string table)where T:SistemaLlantas.Domain.Common.EntidadAuditable{b.ToTable($"TBL_{table}");b.HasKey(x=>x.Id);}
}
