using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using SistemaLlantas.Domain.Entities;
using SistemaLlantas.Infrastructure.Persistence;

namespace SistemaLlantas.Api;
public static class DevelopmentSecuritySeeder
{
 private static readonly SemaphoreSlim SeedGate = new(1,1);
 public static async Task SeedAsync(IServiceProvider services){await SeedGate.WaitAsync();try{using var scope=services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<LlantasDbContext>();await db.Database.MigrateAsync();
  var moduleCodes=new[]{"resumen","actividades","llantas","vehiculos","inventario","inspecciones","alertas","programacion","montajes","movimientos","reparaciones","reencauches","disposicion","historial","carga_masiva","analitica","administracion","auditoria"}.Select(x=>$"modulos.{x}.consultar").ToArray();
  var permissionCodes=new[]{"centros.ver_todos","llantas.consultar","llantas.administrar","vehiculos.consultar","vehiculos.administrar","catalogos.administrar","inspecciones.consultar","inspecciones.crear","inspecciones.reportar_inconsistencia","inspecciones.autorizar_inconsistencia_llanta","inspecciones.gestionar_evidencias","alertas.consultar","alertas.gestionar","alertas.descartar","programacion.consultar","programacion.administrar","operaciones.solicitar","operaciones.aprobar","operaciones.aprobar_propia","operaciones.montar","servicios_llanta.consultar","servicios_llanta.opcionar","servicios_llanta.gestionar","servicios_llanta.aprobar_propia","carga_masiva.importar","reportes.exportar","operaciones.ejecutar","actividades.consultar_propias"}.Concat(moduleCodes).ToArray();
  foreach(var code in permissionCodes)if(!await db.PermisosSistema.AnyAsync(x=>x.Codigo==code))db.PermisosSistema.Add(new(){Codigo=code,Nombre=code,UsuarioCreacion="seed-development"});await db.SaveChangesAsync();
  var tecnicoModules=new[]{"resumen","actividades","llantas","inspecciones","montajes","movimientos","reparaciones","historial"}.Select(x=>$"modulos.{x}.consultar");
  var supervisorModules=new[]{"resumen","actividades","llantas","vehiculos","inventario","inspecciones","alertas","programacion","montajes","movimientos","reparaciones","reencauches","disposicion","historial","analitica"}.Select(x=>$"modulos.{x}.consultar");
  var supervisorAdminModules=new[]{"resumen","actividades","llantas","inventario","inspecciones","alertas","movimientos","reparaciones","reencauches","disposicion","historial","carga_masiva","analitica","auditoria"}.Select(x=>$"modulos.{x}.consultar");
  var map=new Dictionary<string,string[]>{{"TECNICO",new[]{"llantas.consultar","inspecciones.consultar","inspecciones.crear","inspecciones.reportar_inconsistencia","operaciones.solicitar","operaciones.montar","operaciones.ejecutar","servicios_llanta.consultar","servicios_llanta.opcionar","actividades.consultar_propias"}.Concat(tecnicoModules).ToArray()},{"SUPERVISOR",new[]{"llantas.consultar","vehiculos.consultar","inspecciones.consultar","inspecciones.autorizar_inconsistencia_llanta","inspecciones.gestionar_evidencias","alertas.consultar","alertas.gestionar","programacion.consultar","programacion.administrar","operaciones.solicitar","operaciones.aprobar","operaciones.montar","servicios_llanta.consultar","servicios_llanta.gestionar","reportes.exportar","actividades.consultar_propias"}.Concat(supervisorModules).ToArray()},{"SUPERVISOR_ADMINISTRADOR",new[]{"llantas.consultar","llantas.administrar","inspecciones.consultar","inspecciones.crear","inspecciones.reportar_inconsistencia","inspecciones.autorizar_inconsistencia_llanta","inspecciones.gestionar_evidencias","alertas.consultar","alertas.gestionar","alertas.descartar","operaciones.solicitar","operaciones.aprobar","servicios_llanta.consultar","servicios_llanta.gestionar","carga_masiva.importar","reportes.exportar","operaciones.ejecutar","actividades.consultar_propias"}.Concat(supervisorAdminModules).ToArray()},{"ADMINISTRADOR",permissionCodes}};
  foreach(var pair in map){var role=await db.RolesSistema.Include(x=>x.Permisos).ThenInclude(x=>x.Permiso).SingleOrDefaultAsync(x=>x.Codigo==pair.Key);if(role is null){role=new(){Codigo=pair.Key,Nombre=pair.Key switch{"TECNICO"=>"Técnico","SUPERVISOR"=>"Supervisor","SUPERVISOR_ADMINISTRADOR"=>"Supervisor administrador",_=>"Administrador"},UsuarioCreacion="seed-development"};db.RolesSistema.Add(role);await db.SaveChangesAsync();}var ids=await db.PermisosSistema.Where(x=>pair.Value.Contains(x.Codigo)).Select(x=>x.Id).ToListAsync();foreach(var stale in role.Permisos.Where(x=>permissionCodes.Contains(x.Permiso.Codigo)&&!pair.Value.Contains(x.Permiso.Codigo)).ToList())db.RolesPermisos.Remove(stale);foreach(var id in ids.Where(id=>role.Permisos.All(x=>x.PermisoId!=id)))db.RolesPermisos.Add(new(){RolId=role.Id,PermisoId=id});}await db.SaveChangesAsync();
  var users=new[]{("tecnico","Laura Ruiz","TECNICO","tec123"),("supervisor","Carlos Mendoza","SUPERVISOR","super123"),("supervisoradmin","Supervisor administrador local","SUPERVISOR_ADMINISTRADOR","supadmin123"),("administrador","Isabel Martínez","ADMINISTRADOR","admin123")};var hasher=new PasswordHasher<UsuarioSistema>();foreach(var seed in users)if(!await db.UsuariosSistema.AnyAsync(x=>x.Username==seed.Item1)){var role=await db.RolesSistema.SingleAsync(x=>x.Codigo==seed.Item3);var user=new UsuarioSistema{Username=seed.Item1,Nombre=seed.Item2,RolId=role.Id,UsuarioCreacion="seed-development"};user.PasswordHash=hasher.HashPassword(user,seed.Item4);db.UsuariosSistema.Add(user);}await db.SaveChangesAsync();}finally{SeedGate.Release();}}
}
