import {HttpClient} from '@angular/common/http';
import {MountAssignment,MountAssignmentEditor} from '../movements/mount-assignment';
import {CommonModule} from '@angular/common';
import {Component,OnInit,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {firstValueFrom} from 'rxjs';
import {AuthService} from '../../core/auth/auth.service';
import {CatalogsApi} from '../../core/services/catalogs-api';
import {DataTableToolbar,TableFilter} from '../../shared/data-table-toolbar';
import {SingleSelectFilter} from '../../shared/single-select-filter';
import {VehiclesApi,VehicleSummary,VehicleDetail} from '../vehicles/vehicles-api';
import {Schedule,ScheduleInput,ScheduleNeed,SchedulingApi,Technician} from './scheduling-api';
interface Option{id:string;nombre:string} interface PlanRow extends ScheduleNeed{selected:boolean;technicianId:string;start:string;priority:string;error:string}
@Component({selector:'app-scheduling-page',imports:[CommonModule,FormsModule,DataTableToolbar,SingleSelectFilter,MountAssignmentEditor],templateUrl:'./scheduling-page.html',styleUrl:'./scheduling-page.scss'})
export class SchedulingPage implements OnInit{
 private http=inject(HttpClient);
 private api=inject(SchedulingApi);private catalogs=inject(CatalogsApi);private vehiclesApi=inject(VehiclesApi);readonly auth=inject(AuthService);
 rows=signal<Schedule[]>([]);centers=signal<Option[]>([]);vehicles=signal<VehicleSummary[]>([]);technicians=signal<Technician[]>([]);needs=signal<PlanRow[]>([]);message=signal('');loading=signal(true);view=signal<'list'|'calendar'>('list');tab=signal('Programada');modal=signal(false);wizard=signal(false);step=signal(1);saving=signal(false);result=signal<{created:number;errors:string[]}|null>(null);search='';filterValues:Record<string,unknown>={estados:['Programada']};sortBy='inicio';batch={technicianId:'',start:'',priority:'Media'};form=this.emptyForm();
 mountModal=signal(false);mountStep=signal(1);mountVehicle=signal<VehicleDetail|null>(null);mountRows:MountAssignment[]=[];mountReason='';mountSearch='';mountLoading=signal(false);private mountVersion=0;
 readonly priorities=['Baja','Media','Alta','Crítica'];readonly types=['Inspección','Cambio de juego','Reemplazar llanta','Montaje','Desmontaje','Movimiento','Administrativa'];readonly tabs=[['Pendiente','Pendientes'],['Programada','Programadas'],['EnEjecucion','En ejecución'],['Finalizada','Finalizadas'],['Cancelada','Canceladas']];
 readonly typeOptions=this.types.map(x=>({value:x,label:x}));readonly priorityOptions=this.priorities.map(x=>({value:x,label:x}));readonly originOptions=['MANUAL','PREVENTIVO','INSPECCION','ALERTA','INCONSISTENCIA','SOLICITUD'].map(x=>({value:x,label:x}));
 readonly vehicleOptions=computed(()=>this.vehicles().map(v=>({value:v.id,label:`${v.placa} · ${v.numeroInterno} · ${v.centro}`})));readonly centerOptions=computed(()=>this.centers().map(c=>({value:c.id,label:c.nombre})));readonly technicianOptions=computed(()=>this.technicians().filter(t=>!this.form.centroId||t.centroIds.includes(this.form.centroId)).map(t=>({value:t.id,label:t.nombre})));
 readonly filters=computed<TableFilter[]>(()=>[{key:'centros',label:'Centro',type:'multi',options:this.centers().map(x=>({value:x.id,label:x.nombre}))},{key:'estados',label:'Estado',type:'multi',options:this.tabs.map(x=>({value:x[0],label:x[1]}))},{key:'tipos',label:'Tipo',type:'multi',options:this.types.map(x=>({value:x,label:x}))},{key:'prioridades',label:'Prioridad',type:'multi',options:this.priorities.map(x=>({value:x,label:x}))},{key:'tecnicos',label:'Técnico',type:'multi',options:this.technicians().map(x=>({value:x.id,label:x.nombre}))},{key:'origenes',label:'Origen',type:'multi',options:this.originOptions},{key:'fecha',label:'Fecha',type:'range'}]);
 readonly visibleRows=computed(()=>this.rows().filter(x=>{const v=this.filterValues,text=this.search.toLowerCase();const match=(key:string,value:string)=>!(v[key] as string[]|undefined)?.length||(v[key] as string[]).includes(value);return(!text||x.vehiculo.toLowerCase().includes(text))&&match('centros',x.centroId)&&match('estados',x.estado)&&match('tipos',x.tipo)&&match('prioridades',x.prioridad)&&match('tecnicos',x.tecnicoUsuarioId??'')&&match('origenes',x.origen??'')}));
 readonly metrics=computed(()=>{const now=new Date(),today=now.toISOString().slice(0,10),r=this.rows();return{pending:this.needs().length,today:r.filter(x=>x.inicio.slice(0,10)===today).length,overdue:r.filter(x=>x.estado==='Vencida'||(x.estado==='Pendiente'&&new Date(x.inicio)<now)).length,high:r.filter(x=>['Alta','Crítica'].includes(x.prioridad)).length,unassigned:r.filter(x=>!x.tecnicoUsuarioId).length}});
 readonly workload=computed(()=>this.technicians().map(t=>({name:t.nombre,count:this.rows().filter(x=>x.tecnicoUsuarioId===t.id&&!['Cumplida','Cancelada'].includes(x.estado)).length,overdue:this.rows().filter(x=>x.tecnicoUsuarioId===t.id&&x.estado==='Vencida').length})).sort((a,b)=>b.count-a.count));readonly selected=computed(()=>this.needs().filter(x=>x.selected));readonly ready=computed(()=>this.selected().filter(x=>!x.error&&x.technicianId&&x.start));
 async ngOnInit(){try{const[c,v,t,n]=await Promise.all([firstValueFrom(this.catalogs.all('centros',true)),firstValueFrom(this.vehiclesApi.list()),firstValueFrom(this.api.technicians()),firstValueFrom(this.api.needs())]);this.centers.set(c.map(x=>({id:x.id,nombre:`${x.codigo} · ${x.nombre}`})));this.vehicles.set(v.items);this.technicians.set(t);this.needs.set(n.map(x=>({...x,selected:false,technicianId:'',start:'',priority:x.prioridad,error:''})));await this.load()}catch(e:any){this.message.set(e?.userMessage??'No fue posible cargar Programación.')}finally{this.loading.set(false)}}
 async load(){const rows=await firstValueFrom(this.api.list({}));const groups=new Set<string>();this.rows.set(rows.filter(x=>{if(x.tipo!=='Cambio de juego'||!x.grupoProgramacionId)return true;if(groups.has(x.grupoProgramacionId))return false;groups.add(x.grupoProgramacionId);return true;}))} setTab(v:string){this.tab.set(v);this.filterValues={...this.filterValues,estados:[v]}} clear(){this.search='';this.filterValues={estados:[this.tab()]}} canManage(){return this.auth.has('programacion.administrar')}
 applyFilters(){this.filterValues={...this.filterValues}} openNew(){this.form=this.emptyForm();this.modal.set(true)} edit(x:Schedule){if(x.tipo==='Montaje'||x.tipo==='Reemplazar llanta'||x.tipo==='Cambio de juego'){this.message.set('Para modificar asignaciones, cancela el trabajo completo y vuelve a programarlo.');return;}this.form={id:x.id,tipo:x.tipo,inicio:this.local(x.inicio),fin:this.local(x.fin??x.inicio),centroId:x.centroId,vehicleId:x.vehiculoId??'',tecnicoUsuarioId:x.tecnicoUsuarioId??'',prioridad:x.prioridad,observaciones:x.observaciones??'',origen:x.origen??'MANUAL',origenEntidadId:x.origenEntidadId??'',rowVersion:x.rowVersion};this.modal.set(true)}
 async save(){if(!this.form.centroId||!this.form.tecnicoUsuarioId||!this.form.inicio||!this.form.fin)return this.message.set('Completa los campos obligatorios.');this.saving.set(true);try{const input=this.input(this.form);if(this.form.id)await firstValueFrom(this.api.update(this.form.id,input));else await firstValueFrom(this.api.create(input));this.modal.set(false);await this.load();this.message.set('Programación guardada.')}catch(e:any){this.message.set(e?.userMessage??'No fue posible guardar.')}finally{this.saving.set(false)}}
 openWizard(){this.step.set(1);this.result.set(null);this.wizard.set(true)} toggle(n:PlanRow){n.selected=!n.selected;this.needs.set([...this.needs()])} selectAll(){const all=this.needs().every(x=>x.selected);this.needs.update(rows=>rows.map(x=>({...x,selected:!all})))} applyBatch(){this.needs.update(rows=>rows.map(x=>x.selected?{...x,technicianId:this.batch.technicianId||x.technicianId,start:this.batch.start||x.start,priority:this.batch.priority||x.priority}:x));this.validateRows()}
 validateRows(){const seen=new Set<string>();this.needs.update(rows=>rows.map(x=>{if(!x.selected)return x;let error='';if(x.tipo==='Montaje'||x.tipo==='Reemplazar llanta'||x.tipo==='Cambio de juego')error='Usa Programar montaje para asignar llantas antes de guardar';else if(!x.technicianId||!x.start)error='Falta técnico o fecha';else if(!this.technicians().some(t=>t.id===x.technicianId&&t.centroIds.includes(x.centroId)))error='Técnico fuera del centro';const key=`${x.id}|${x.technicianId}|${x.start}`;if(seen.has(key))error='Duplicada en el lote';seen.add(key);return{...x,error}}))} next(){if(this.step()===2)this.validateRows();this.step.update(x=>Math.min(4,x+1))} back(){this.step.update(x=>Math.max(1,x-1))}
 async confirm(){this.validateRows();const ready=this.ready();if(!ready.length)return;this.saving.set(true);const errors:string[]=[];let created=0;for(const x of ready){try{await firstValueFrom(this.api.create({tipo:x.tipo,inicio:new Date(x.start).toISOString(),fin:new Date(new Date(x.start).getTime()+3600000).toISOString(),centroId:x.centroId,vehiculoId:x.vehiculoId,tecnicoUsuarioId:x.technicianId,prioridad:x.priority,observaciones:x.motivo,origen:x.origen,origenEntidadId:x.id,idempotencyKey:`plan-${x.origen}-${x.id}`}));created++}catch(e:any){errors.push(`${x.vehiculo}: ${e?.userMessage??'conflicto'}`)}}this.result.set({created,errors});this.step.set(4);this.saving.set(false);await this.load();if(created)this.needs.update(rows=>rows.filter(x=>!ready.some(r=>r.id===x.id)||errors.some(e=>e.startsWith(x.vehiculo))))}
 async cancel(x:Schedule){const motivo=prompt('Motivo obligatorio de cancelación:')?.trim();if(motivo){await firstValueFrom(this.api.cancel(x.id,motivo));await this.load()}} techs(center:string){return this.technicians().filter(x=>x.centroIds.includes(center))} input(f:any):ScheduleInput{return{tipo:f.tipo,inicio:new Date(f.inicio).toISOString(),fin:new Date(f.fin).toISOString(),centroId:f.centroId,vehiculoId:f.vehicleId||null,tecnicoUsuarioId:f.tecnicoUsuarioId,prioridad:f.prioridad,observaciones:f.observaciones||null,origen:f.origen||'MANUAL',origenEntidadId:f.origenEntidadId||null,rowVersion:f.rowVersion}} emptyForm(){return{id:'',tipo:'Inspección',inicio:'',fin:'',centroId:'',vehicleId:'',tecnicoUsuarioId:'',prioridad:'Media',observaciones:'',origen:'MANUAL',origenEntidadId:'',rowVersion:undefined as string|undefined}} local(v:string){const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)} date(v:string){return new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short'}).format(new Date(v))} time(v:string){return new Intl.DateTimeFormat('es-CO',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))}
 openMount(){this.form=this.emptyForm();this.form.tipo='Montaje';this.mountStep.set(1);this.mountRows=[];this.mountReason='';this.mountVehicle.set(null);this.mountModal.set(true);this.message.set('');}
 changeType(value:string){this.form.tipo=value;if(value==='Montaje'||value==='Reemplazar llanta'||value==='Cambio de juego'){this.modal.set(false);this.openMount();this.form.tipo=value;}}
 async searchMountVehicles(){try{const page=await firstValueFrom(this.http.get<{items:VehicleSummary[]}>('/api/operaciones/vehiculos',{params:{buscar:this.mountSearch,tamano:100}}));this.vehicles.set(page.items);}catch(e:any){this.message.set(e?.userMessage??'No se pudieron buscar vehículos.');}}
 async pickMountVehicle(id:string){const version=++this.mountVersion;this.form.vehicleId=id;this.mountVehicle.set(null);this.mountRows=[];if(!id)return;this.mountLoading.set(true);try{const vehicle=await firstValueFrom(this.http.get<VehicleDetail>('/api/operaciones/vehiculos/'+id));if(version!==this.mountVersion)return;this.mountVehicle.set(vehicle);this.form.centroId=vehicle.centroId;this.form.tecnicoUsuarioId='';}catch(e:any){if(version===this.mountVersion)this.message.set(e?.userMessage??'No se pudo cargar el vehículo.');}finally{if(version===this.mountVersion)this.mountLoading.set(false);}}
 mountNext(){const step=this.mountStep();if(step===1&&!this.mountVehicle())return this.message.set('Selecciona un vehículo.');if(step===3&&(!this.mountRows.length||(this.form.tipo!=='Cambio de juego'&&this.mountRows.length!==1)||(this.form.tipo==='Cambio de juego'&&this.mountRows.length<2)||(this.form.tipo==='Reemplazar llanta'&&this.mountRows.some(x=>!x.llantaActualId))))return this.message.set('Asigna las llantas a montar.');if(step===4&&(!this.mountReason.trim()||!this.form.tecnicoUsuarioId||!this.form.inicio||!this.form.fin||new Date(this.form.fin)<=new Date(this.form.inicio)))return this.message.set('Completa motivo, técnico y un intervalo válido.');this.message.set('');this.mountStep.update(x=>Math.min(5,x+1));}
 async saveMount(){if(this.saving()||!this.mountRows.length)return;if(this.form.tipo==='Cambio de juego'&&this.mountRows.length<2)return this.message.set('Cambio de juego requiere al menos dos posiciones.');if(this.form.tipo==='Reemplazar llanta'&&(this.mountRows.length!==1||!this.mountRows[0].llantaActualId))return this.message.set('Reemplazar llanta requiere una posición ocupada.');this.saving.set(true);try{await firstValueFrom(this.api.create({...this.input(this.form),asignaciones:this.mountRows,motivo:this.mountReason,idempotencyKey:this.mountKey()}));this.mountModal.set(false);await this.load();this.message.set('Montaje programado con llantas asignadas y comprometidas.');}catch(e:any){this.message.set(e?.userMessage??'No fue posible programar.');}finally{this.saving.set(false);}}
 private mountKey(){return this.form.id||(this.form.id=crypto.randomUUID());}

}
