import {TestBed} from '@angular/core/testing';
import {provideRouter,Router} from '@angular/router';
import {of} from 'rxjs';
import {DispositionApi} from './disposition-api';
import {DispositionReview} from './disposition-review';
import {DispositionProposal} from './disposition-proposal';
import {DispositionTable} from './disposition-table';
import {AuthService} from '../../core/auth/auth.service';
describe('Disposición operativa',()=>{
 let api:any;const tire={id:'t',codigo:'LL-1',serial:'S1',centro:'Centro',vehiculo:null,posicion:null};const detail={orden:{codigo:'LL-1'},accionesPermitidas:['APROBAR','RECHAZAR'],evidencias:[],eventos:[]};
 beforeEach(()=>{api={detail:jasmine.createSpy().and.returnValue(of(detail)),approve:jasmine.createSpy().and.returnValue(of({})),reject:jasmine.createSpy().and.returnValue(of({})),file:jasmine.createSpy().and.returnValue(of(new Blob(['image'],{type:'image/png'}))),tires:jasmine.createSpy().and.returnValue(of({items:[tire],pageNumber:1,totalPages:2})),proposals:jasmine.createSpy().and.returnValue(of([{ordenId:'o',llantaId:'t'}])),orders:jasmine.createSpy().and.returnValue(of({items:[{ordenId:'o',codigo:'LL-1',serial:'S1',centroOrigen:{nombre:'Centro'},estado:'PENDIENTE_APROBACION',etiqueta:'Pendiente de aprobación',evidencias:3}],pageNumber:1,totalPages:1,totalItems:1})),facets:jasmine.createSpy().and.returnValue(of({items:[],pageNumber:1,totalPages:0}))};TestBed.configureTestingModule({providers:[provideRouter([]),{provide:DispositionApi,useValue:api},{provide:AuthService,useValue:{has:()=>true}}]})});
 it('aprobar exige revisión; rechazo exige motivo',async()=>{const c=TestBed.createComponent(DispositionReview).componentInstance;c.id='o';c.data.set(detail as any);c.loading.set(false);await c.run('APROBAR');await c.run('RECHAZAR');expect(api.approve).not.toHaveBeenCalled();expect(api.reject).not.toHaveBeenCalled();c.reviewed=true;await c.run('APROBAR');expect(api.approve).toHaveBeenCalledOnceWith('o');c.notes='No procede';await c.run('RECHAZAR');expect(api.reject).toHaveBeenCalledOnceWith('o','No procede')});
 it('carga miniaturas autenticadas y libera URLs',async()=>{api.detail.and.returnValue(of({...detail,evidencias:[{id:'e',mimeType:'image/png',nombreArchivo:'foto.png'}]}));spyOn(URL,'createObjectURL').and.returnValue('blob:test');const revoke=spyOn(URL,'revokeObjectURL');const c=TestBed.createComponent(DispositionReview).componentInstance;c.id='o';await c.load();expect(api.file).toHaveBeenCalledWith('e',true);expect(c.images().length).toBe(1);c.ngOnDestroy();expect(revoke).toHaveBeenCalledWith('blob:test')});
 it('abre PDF autorizado en otra pestaña',async()=>{const tab={opener:null,location:{href:''},close:()=>{}};spyOn(window,'open').and.returnValue(tab as any);spyOn(URL,'createObjectURL').and.returnValue('blob:pdf');const c=TestBed.createComponent(DispositionReview).componentInstance;await c.open({id:'pdf',mimeType:'application/pdf'} as any);expect(api.file).toHaveBeenCalledWith('pdf',true);expect(tab.location.href).toBe('blob:pdf')});
 it('preserva selección entre páginas y crea órdenes independientes una sola vez',async()=>{const c=TestBed.createComponent(DispositionProposal).componentInstance;await c.load();c.choose(['t']);api.tires.and.returnValue(of({items:[{...tire,id:'t2',codigo:'LL-2'}],pageNumber:2,totalPages:2}));c.search='LL-2';await c.load(true);c.choose(['t','t2']);expect(c.selected().map(t=>t.id)).toEqual(['t','t2']);c.reason='Motivo';c.notes='Observación';await c.create();expect(api.proposals.calls.mostRecent().args[0].length).toBe(2);await c.create();expect(api.proposals).toHaveBeenCalledTimes(1)});
 it('renderiza tabla sin pedir detalle por fila',async()=>{const f=TestBed.createComponent(DispositionTable);f.detectChanges();await f.whenStable();f.detectChanges();expect(f.nativeElement.querySelector('tbody').textContent).toContain('LL-1');expect(f.nativeElement.textContent).toContain('Ver evidencia (3)');expect(api.detail).not.toHaveBeenCalled()});
 it('serializa filtros múltiples, búsqueda y todos los resultados',()=>{const nav=spyOn(TestBed.inject(Router),'navigate').and.resolveTo(true);const c=TestBed.createComponent(DispositionTable).componentInstance;c.search='LL-1';c.set('centroIds',['a','b']);expect(nav.calls.mostRecent().args[1]?.queryParams?.['centroIds']).toEqual(['a','b']);c.selectMatches('llanta','LL-');expect(nav.calls.mostRecent().args[1]?.queryParams?.['llantaTexto']).toBe('LL-');expect(nav.calls.mostRecent().args[1]?.queryParams?.['buscar']).toBe('LL-1')});
});
