import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { DiagramAxle, DiagramPosition, VehicleAxleDiagram } from '../../shared/vehicle-axle-diagram';
import { AuthService } from '../../core/auth/auth.service';
import { ActivatedRoute } from '@angular/router';

interface TireInspection extends DiagramPosition { outer:number|null; center:number|null; inner:number|null; condition:string; cause:string; recommendation:string; notes:string }
interface InspectionVehicle { id:string; internal:string; plate:string; description:string; type:string; centerCode:string; centerName:string }
interface ApiVehicle { id:string; numeroInterno:string; placa:string; tipo:string; centroCodigo:string; centroNombre:string }
interface ApiContext { vehiculoId:string;numeroInterno:string;placa:string;tipo:string;centroNombre:string;ejes:Array<{id:string;numero:number;nombre:string;posiciones:Array<{id:string;codigo:string;lado:string;orden:number;llanta:{id:string;codigo:string;estado:string}|null}>}> }
interface ApiOption { id:string;codigo:string;nombre:string }
interface ApiOptions { condiciones:ApiOption[];causas:ApiOption[];recomendaciones:ApiOption[] }
interface ApiInspection { id:string }
interface ApiEvidence{id:string;nombreArchivo:string;mimeType:string;tamanoBytes:number;hash:string;fecha:string;activo:boolean}

@Component({selector:'app-inspection-page',imports:[FormsModule,VehicleAxleDiagram],template:`
<main class="inspection-page">
 <header class="title"><div><p>CONTROL TÉCNICO</p><h1>Nueva inspección</h1><span>Registra la condición de cada llanta de forma clara y segura.</span></div><div class="progress"><b>{{completed()}} / {{positions().length}}</b><small>posiciones revisadas</small></div></header>
 <section class="context card">
  <header class="context-heading"><div><small>DATOS DE LA OPERACIÓN</small><h2>Resumen de la inspección</h2></div><span>Confirma el vehículo y registra la lectura actual antes de guardar.</span></header>
  <div class="context-item"><small>CENTRO DE TRABAJO</small><b>{{vehicle().centerName}}</b><span>Código {{vehicle().centerCode}}</span></div>
  <div class="vehicle-selector context-item"><small>VEHÍCULO</small><label class="vehicle-search"><span class="sr-only">Buscar vehículo</span><input type="search" [ngModel]="vehicleSearch()" (ngModelChange)="vehicleSearch.set($event)" placeholder="Buscar por interno, placa, tipo o centro" autocomplete="off" aria-controls="inspection-vehicle-select">@if(vehicleSearch()){<button type="button" (click)="vehicleSearch.set('')" aria-label="Limpiar búsqueda de vehículo">×</button>}</label><label class="sr-only" for="inspection-vehicle-select">Seleccionar vehículo</label><select id="inspection-vehicle-select" [ngModel]="selectedVehicleId()" (ngModelChange)="changeVehicle($event)" [disabled]="filteredVehicles().length===0">@for(item of filteredVehicles();track item.id){<option [value]="item.id">Interno {{item.internal}} - {{item.plate}}</option>}</select>@if(filteredVehicles().length===0){<span class="search-status" role="status">No se encontraron vehículos. Prueba otro término.</span>}@else{<span class="search-status" aria-live="polite">{{filteredVehicles().length}} {{filteredVehicles().length===1?'vehículo encontrado':'vehículos encontrados'}} · {{vehicle().description}} · {{vehicle().type}}</span>}</div>
  <label class="context-item"><small>KILOMETRAJE ACTUAL</small><input type="number" min="0" [(ngModel)]="mileage" placeholder="Es obligatorio ingresarlo"><span>Lectura del odómetro al iniciar</span></label>
 </section>
 <section class="workspace"><aside class="card vehicle"><div class="section-title"><div><small>CONFIGURACIÓN DEL VEHÍCULO</small><h2>Selecciona una posición</h2></div><span>{{axles().length}} ejes · {{positions().length}} llantas</span></div><app-vehicle-axle-diagram [axles]="axles()" [selectedId]="selected().id" [vehicleType]="vehicle().type" (positionSelected)="select($event)"/><p class="hint">Toca una llanta para cargar sus datos. Los cambios permanecen guardados mientras avanzas.</p></aside>
 <section class="card editor"><div class="tire-head"><div class="position"><small>POSICIÓN</small><b>{{selected().code}}</b></div><div><small>LLANTA INSTALADA</small><h2>{{selected().tire}}</h2><span class="mounted">● Montada · Operativa</span></div></div>
  <div class="measure-title"><div><small>PROFUNDIDAD DE LABRADO</small><h3>Selecciona las medidas en milímetros</h3></div><span>Exterior · Centro · Interior</span></div>
  <div class="measures"><label>Exterior<select [(ngModel)]="selected().outer"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label><label>Centro<select [(ngModel)]="selected().center"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label><label>Interior<select [(ngModel)]="selected().inner"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label></div>
  <div class="fields"><label><span>Condición / novedad</span><select [(ngModel)]="selected().condition"><option value="">Seleccionar...</option>@for(item of options().condiciones;track item.id){<option [value]="item.id">{{item.nombre}}</option>}</select></label><label><span>Causa</span><select [(ngModel)]="selected().cause"><option value="">Seleccionar cuando aplique...</option>@for(item of options().causas;track item.id){<option [value]="item.id">{{item.nombre}}</option>}</select></label><label class="wide"><span>Recomendación</span><select [(ngModel)]="selected().recommendation"><option value="">Seleccionar...</option>@for(item of options().recomendaciones;track item.id){<option [value]="item.id">{{item.nombre}}</option>}</select></label><label class="wide"><span>Observaciones</span><textarea rows="3" [(ngModel)]="selected().notes" placeholder="Describe el hallazgo con palabras claras"></textarea></label></div>
  <div class="actions"><button class="mismatch" type="button" (click)="mismatchOpen.set(true)"><b>⚠ REPORTAR LLANTA DIFERENTE</b><small>La llanta física no coincide con la registrada</small></button><input #evidenceInput class="sr-only" type="file" accept="image/jpeg,image/png,application/pdf" (change)="uploadEvidence($event)"><button class="photo" type="button" [disabled]="uploadingEvidence()" (click)="evidenceInput.click()">{{uploadingEvidence()?'Adjuntando…':'＋ Adjuntar evidencia'}}</button></div>
  @if(evidences().length){<div class="evidence-list">@for(e of evidences();track e.id){<span><b>{{e.nombreArchivo}}</b><small>{{e.mimeType}} · {{e.tamanoBytes}} bytes</small><button type="button" (click)="downloadEvidence(e)">Descargar</button>@if(auth.has('inspecciones.gestionar_evidencias')){<button type="button" (click)="deleteEvidence(e)">Eliminar</button>}</span>}</div>}
  <footer><button class="previous" type="button" (click)="previous()">← Anterior</button><button class="save" type="button" (click)="savePosition()">Guardar posición y continuar →</button></footer>
 </section></section>
 @if(message()){<div class="toast">✓ {{message()}}</div>}
 @if(mismatchOpen()){<div class="overlay"><section class="modal"><header><div><small>ALERTA DE TRAZABILIDAD</small><h2>Reportar llanta diferente</h2></div><button (click)="mismatchOpen.set(false)">×</button></header><div class="expected"><span>Posición {{selected().code}}</span><b>Llanta esperada: {{selected().tire}}</b><small>No será reemplazada automáticamente.</small></div><label>Identificador encontrado<input [(ngModel)]="foundTire" placeholder="Ej. LL-00987" autofocus></label><label>Observación obligatoria<textarea [(ngModel)]="mismatchNotes" rows="4" placeholder="Explique qué encontró físicamente"></textarea></label><label class="evidence">＋ Adjuntar fotografía o evidencia</label><footer><button (click)="mismatchOpen.set(false)">Cancelar</button><button class="alert" [disabled]="!foundTire.trim()||!mismatchNotes.trim()" (click)="reportMismatch()">Crear alerta y llanta temporal</button></footer></section></div>}
</main>`,styleUrls:['./inspection-page.scss','./inspection-controls.scss']})
export class InspectionPage implements OnInit{
 private http=inject(HttpClient);
 private route=inject(ActivatedRoute);
 readonly auth=inject(AuthService);
 readonly depthOptions=Array.from({length:51},(_,index)=>index*.5);
 private inspectionId:string|null=null;
 vehicles=signal<InspectionVehicle[]>([]);
 options=signal<ApiOptions>({condiciones:[],causas:[],recomendaciones:[]});
 mileage:number|null=null;mismatchOpen=signal(false);uploadingEvidence=signal(false);foundTire='';mismatchNotes='';vehicleSearch=signal('');message=signal('Conectando con SQL Server...');selectedVehicleId=signal('');selectedId=signal<number|string>(1);positions=signal<TireInspection[]>([this.emptyPosition()]);axles=signal<DiagramAxle[]>([]);
 evidences=signal<ApiEvidence[]>([]);
 vehicle=computed(()=>this.vehicles().find(item=>item.id===this.selectedVehicleId())??this.vehicles()[0]??{id:'',internal:'—',plate:'—',description:'Sin vehículo asociado',type:'Vehículo',centerCode:'—',centerName:'Sin centro'});selected=computed(()=>this.positions().find(item=>item.id===this.selectedId())??this.positions()[0]??this.emptyPosition());completed=computed(()=>this.positions().filter(item=>item.condition&&item.recommendation).length);
 filteredVehicles=computed(()=>{const term=this.normalize(this.vehicleSearch());if(!term)return this.vehicles();return this.vehicles().filter(item=>this.normalize([item.internal,item.plate,item.description,item.type,item.centerCode,item.centerName].join(' ')).includes(term))});
 async ngOnInit(){try{const [vehicles,options]=await Promise.all([firstValueFrom(this.http.get<ApiVehicle[]>('/api/inspecciones/vehiculos')),firstValueFrom(this.http.get<ApiOptions>('/api/inspecciones/opciones'))]);this.vehicles.set(vehicles.map(v=>({id:v.id,internal:v.numeroInterno,plate:v.placa,description:v.tipo,type:v.tipo,centerCode:v.centroCodigo,centerName:v.centroNombre})));this.options.set(options);const requested=this.route.snapshot.queryParamMap.get('vehiculoId');const selected=vehicles.find(v=>v.id===requested)??vehicles[0];if(selected)await this.changeVehicle(selected.id);else this.message.set('No hay vehículos activos asociados a tus actividades y centro de trabajo.')}catch{this.message.set('No fue posible conectar con SQL Server. Verifica que el backend esté activo en el puerto 5262.')}}
 async changeVehicle(vehicleId:string){try{const context=await firstValueFrom(this.http.get<ApiContext>(`/api/inspecciones/contexto/${vehicleId}`));this.selectedVehicleId.set(vehicleId);const mapped:TireInspection[]=[];const axles=context.ejes.map(e=>({id:e.id,name:e.nombre,type:e.numero===1?'Direccional':'Tracción',positions:e.posiciones.map(p=>{const item:TireInspection={id:p.id,code:p.codigo,side:p.lado,tire:p.llanta?.codigo??'SIN LLANTA',state:p.llanta?'normal':'empty',outer:null,center:null,inner:null,condition:'',cause:'',recommendation:'',notes:''};mapped.push(item);return item})}));this.positions.set(mapped);this.axles.set(axles);this.selectedId.set(mapped[0]?.id??1);this.mileage=null;this.inspectionId=null;this.message.set(`Datos cargados desde SQL Server: ${mapped.length} posiciones de ${context.centroNombre}.`)}catch{this.message.set('No se pudo cargar el vehículo desde SQL Server.')}}
 select(item:DiagramPosition){this.selectedId.set(item.id);this.message.set('')}previous(){const index=this.positions().findIndex(x=>x.id===this.selectedId());if(index>0)this.selectedId.set(this.positions()[index-1].id)}
 async savePosition(){const tire=this.selected();if(tire.outer===null||tire.center===null||tire.inner===null){this.message.set('Selecciona las tres profundidades antes de continuar.');return}if(!tire.condition||!tire.recommendation){this.message.set('Selecciona la condición y la recomendación antes de continuar.');return}try{const id=await this.ensureInspection();await firstValueFrom(this.http.put(`/api/inspecciones/${id}/posiciones/${tire.id}`,{profundidadExterior:tire.outer,profundidadCentro:tire.center,profundidadInterior:tire.inner,condicionId:tire.condition,causaId:tire.cause||null,recomendacionId:tire.recommendation,observaciones:tire.notes||null}));this.message.set(`${tire.code} guardada en SQL Server.`);const index=this.positions().findIndex(x=>x.id===tire.id);if(index<this.positions().length-1)this.selectedId.set(this.positions()[index+1].id)}catch{this.message.set('No fue posible guardar. Verifica el backend y los datos obligatorios.')}}
 async reportMismatch(){try{const id=await this.ensureInspection();const tire=this.selected();await firstValueFrom(this.http.post(`/api/inspecciones/${id}/inconsistencias`,{posicionId:tire.id,identificadorEncontrado:this.foundTire,observacion:this.mismatchNotes}));tire.state='inconsistency';this.mismatchOpen.set(false);this.message.set(`Inconsistencia de ${tire.code} guardada en SQL Server y pendiente de autorización.`);this.foundTire='';this.mismatchNotes=''}catch{this.message.set('No fue posible registrar la inconsistencia en SQL Server.')}}
 async uploadEvidence(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;if(!['image/jpeg','image/png','application/pdf'].includes(file.type)){this.message.set('Formato no permitido. Adjunta JPG, PNG o PDF.');input.value='';return}if(file.size>10_000_000){this.message.set('La evidencia supera el límite de 10 MB.');input.value='';return}this.uploadingEvidence.set(true);try{const id=await this.ensureInspection();const body=new FormData();body.append('archivo',file,file.name);await firstValueFrom(this.http.post(`/api/inspecciones/${id}/evidencias`,body));await this.loadEvidences();this.message.set(`Evidencia ${file.name} adjuntada correctamente.`)}catch(error:any){this.message.set(error?.userMessage??'No fue posible adjuntar la evidencia.')}finally{this.uploadingEvidence.set(false);input.value=''}}
 async loadEvidences(){if(this.inspectionId)this.evidences.set(await firstValueFrom(this.http.get<ApiEvidence[]>(`/api/inspecciones/${this.inspectionId}/evidencias`)))}async downloadEvidence(e:ApiEvidence){const blob=await firstValueFrom(this.http.get(`/api/inspecciones/evidencias/${e.id}/archivo`,{responseType:'blob'}));const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=e.nombreArchivo;a.click();URL.revokeObjectURL(url)}async deleteEvidence(e:ApiEvidence){await firstValueFrom(this.http.delete(`/api/inspecciones/evidencias/${e.id}`));await this.loadEvidences()}
 private async ensureInspection(){if(this.inspectionId)return this.inspectionId;const created=await firstValueFrom(this.http.post<ApiInspection>('/api/inspecciones',{vehiculoId:this.selectedVehicleId(),kilometraje:this.mileage,observaciones:null}));this.inspectionId=created.id;return created.id}
 private normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLocaleLowerCase('es')}
 private emptyPosition():TireInspection{return{id:1,code:'—',side:'',tire:'Cargando...',state:'empty',outer:null,center:null,inner:null,condition:'',cause:'',recommendation:'',notes:''}}
}
