import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DiagramAxle, DiagramPosition, VehicleAxleDiagram } from '../../shared/vehicle-axle-diagram';

interface TireInspection extends DiagramPosition { outer:number|null; center:number|null; inner:number|null; condition:string; cause:string; recommendation:string; notes:string }
interface InspectionVehicle { id:string; internal:string; plate:string; description:string; type:string; centerCode:string; centerName:string; axles:Array<{name:string;type:string;tires:number}> }

@Component({selector:'app-inspection-page',imports:[FormsModule,VehicleAxleDiagram],template:`
<main class="inspection-page">
 <header class="title"><div><p>CONTROL TÉCNICO</p><h1>Nueva inspección</h1><span>Registra la condición de cada llanta de forma clara y segura.</span></div><div class="progress"><b>{{completed()}} / {{positions().length}}</b><small>posiciones revisadas</small></div></header>
 <section class="context card">
  <div><small>CENTRO DE TRABAJO</small><b>{{vehicle().centerName}}</b><span>Código {{vehicle().centerCode}}</span></div>
  <label class="vehicle-selector"><small>VEHÍCULO</small><select [ngModel]="selectedVehicleId()" (ngModelChange)="changeVehicle($event)">@for(item of vehicles;track item.id){<option [value]="item.id">Interno {{item.internal}} - {{item.plate}}</option>}</select><span>{{vehicle().description}} · {{vehicle().type}}</span></label>
  <label><small>KILOMETRAJE ACTUAL</small><input type="number" min="0" [(ngModel)]="mileage" placeholder="Es obligatorio ingresarlo"></label>
 </section>
 <section class="workspace"><aside class="card vehicle"><div class="section-title"><div><small>CONFIGURACIÓN DEL VEHÍCULO</small><h2>Selecciona una posición</h2></div><span>{{axles().length}} ejes · {{positions().length}} llantas</span></div><app-vehicle-axle-diagram [axles]="axles()" [selectedId]="selected().id" [vehicleType]="vehicle().type" (positionSelected)="select($event)"/><p class="hint">Toca una llanta para cargar sus datos. Los cambios permanecen guardados mientras avanzas.</p></aside>
 <section class="card editor"><div class="tire-head"><div class="position"><small>POSICIÓN</small><b>{{selected().code}}</b></div><div><small>LLANTA INSTALADA</small><h2>{{selected().tire}}</h2><span class="mounted">● Montada · Operativa</span></div></div>
  <div class="measure-title"><div><small>PROFUNDIDAD DE LABRADO</small><h3>Selecciona las medidas en milímetros</h3></div><span>Exterior · Centro · Interior</span></div>
  <div class="measures"><label>Exterior<select [(ngModel)]="selected().outer"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label><label>Centro<select [(ngModel)]="selected().center"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label><label>Interior<select [(ngModel)]="selected().inner"><option [ngValue]="null">Seleccionar</option>@for(value of depthOptions;track value){<option [ngValue]="value">{{value.toFixed(1)}} mm</option>}</select></label></div>
  <div class="fields"><label><span>Condición / novedad</span><select [(ngModel)]="selected().condition"><option value="">Seleccionar...</option><option>Sin novedad</option><option>Desgaste irregular</option><option>Corte</option><option>Perforación</option><option>Golpe</option><option>Deformación</option><option>Separación</option><option>Daño lateral</option><option>Otro</option></select></label><label><span>Causa</span><select [(ngModel)]="selected().cause"><option value="">Seleccionar cuando aplique...</option><option>Problema de alineación</option><option>Presión incorrecta</option><option>Sobrecarga</option><option>Daño en suspensión</option><option>Elemento externo</option><option>Por determinar</option></select></label><label class="wide"><span>Recomendación</span><select [(ngModel)]="selected().recommendation"><option value="">Seleccionar...</option><option>Continuar operación</option><option>Realizar seguimiento</option><option>Rotar</option><option>Reparar</option><option>Desmontar</option><option>Enviar a reencauche</option><option>Revisar por supervisor</option></select></label><label class="wide"><span>Observaciones</span><textarea rows="3" [(ngModel)]="selected().notes" placeholder="Describe el hallazgo con palabras claras"></textarea></label></div>
  <div class="actions"><button class="mismatch" type="button" (click)="mismatchOpen.set(true)"><b>⚠ REPORTAR LLANTA DIFERENTE</b><small>La llanta física no coincide con la registrada</small></button><button class="photo" type="button">＋ Adjuntar evidencia</button></div>
  <footer><button class="previous" type="button" (click)="previous()">← Anterior</button><button class="save" type="button" (click)="savePosition()">Guardar posición y continuar →</button></footer>
 </section></section>
 @if(message()){<div class="toast">✓ {{message()}}</div>}
 @if(mismatchOpen()){<div class="overlay"><section class="modal"><header><div><small>ALERTA DE TRAZABILIDAD</small><h2>Reportar llanta diferente</h2></div><button (click)="mismatchOpen.set(false)">×</button></header><div class="expected"><span>Posición {{selected().code}}</span><b>Llanta esperada: {{selected().tire}}</b><small>No será reemplazada automáticamente.</small></div><label>Identificador encontrado<input [(ngModel)]="foundTire" placeholder="Ej. LL-00987" autofocus></label><label>Observación obligatoria<textarea [(ngModel)]="mismatchNotes" rows="4" placeholder="Explique qué encontró físicamente"></textarea></label><label class="evidence">＋ Adjuntar fotografía o evidencia</label><footer><button (click)="mismatchOpen.set(false)">Cancelar</button><button class="alert" [disabled]="!foundTire.trim()||!mismatchNotes.trim()" (click)="reportMismatch()">Crear alerta y llanta temporal</button></footer></section></div>}
</main>`,styleUrls:['./inspection-page.scss','./inspection-controls.scss']})
export class InspectionPage{
 readonly depthOptions=Array.from({length:51},(_,index)=>index*.5);
 readonly vehicles:InspectionVehicle[]=[
  {id:'1542',internal:'1542',plate:'ABC123',description:'Kenworth T680',type:'Tractocamión',centerCode:'8092',centerName:'EDINSA MEDELLÍN',axles:[{name:'EJE 1',type:'Direccional',tires:2},{name:'EJE 2',type:'Tracción',tires:4},{name:'EJE 3',type:'Tracción',tires:4}]},
  {id:'2450',internal:'2450',plate:'JKL908',description:'Chevrolet FVR',type:'Camión rígido',centerCode:'8279',centerName:'POSTOBON BELLO',axles:[{name:'EJE 1',type:'Direccional',tires:2},{name:'EJE 2',type:'Tracción',tires:4}]},
  {id:'3190',internal:'3190',plate:'MNO317',description:'Freightliner M2',type:'Camión rígido',centerCode:'8092',centerName:'EDINSA MEDELLÍN',axles:[{name:'EJE 1',type:'Direccional',tires:2},{name:'EJE 2',type:'Tracción',tires:4}]}
 ];
 mileage:number|null=null;mismatchOpen=signal(false);foundTire='';mismatchNotes='';message=signal('');selectedVehicleId=signal(this.vehicles[0].id);selectedId=signal(1);positions=signal<TireInspection[]>(this.createPositions(this.vehicles[0]));
 vehicle=computed(()=>this.vehicles.find(item=>item.id===this.selectedVehicleId())??this.vehicles[0]);selected=computed(()=>this.positions().find(item=>item.id===this.selectedId())??this.positions()[0]);completed=computed(()=>this.positions().filter(item=>item.condition&&item.recommendation).length);
 axles=computed<DiagramAxle[]>(()=>{let offset=0;return this.vehicle().axles.map((axle,index)=>{const positions=this.positions().slice(offset,offset+axle.tires);offset+=axle.tires;return{id:index+1,name:axle.name,type:axle.type,positions}})});
 changeVehicle(vehicleId:string){const next=this.vehicles.find(item=>item.id===vehicleId);if(!next)return;this.selectedVehicleId.set(vehicleId);this.positions.set(this.createPositions(next));this.selectedId.set(1);this.mileage=null;this.message.set(`Vehículo cambiado. Se cargaron ${this.positions().length} posiciones de ${next.centerName}.`)}
 select(item:DiagramPosition){this.selectedId.set(Number(item.id));this.message.set('')}previous(){this.selectedId.update(value=>Math.max(1,value-1))}
 savePosition(){const tire=this.selected();if(tire.outer===null||tire.center===null||tire.inner===null){this.message.set('Selecciona las tres profundidades antes de continuar.');return}if(!tire.condition||!tire.recommendation){this.message.set('Selecciona la condición y la recomendación antes de continuar.');return}this.message.set(`${tire.code} guardada correctamente.`);this.selectedId.update(value=>Math.min(this.positions().length,value+1))}
 reportMismatch(){this.selected().state='inconsistency';this.mismatchOpen.set(false);this.message.set(`Inconsistencia creada para ${this.selected().code}. La llanta temporal quedó pendiente de autorización.`);this.foundTire='';this.mismatchNotes=''}
 private createPositions(vehicle:InspectionVehicle):TireInspection[]{const total=vehicle.axles.reduce((sum,axle)=>sum+axle.tires,0);return Array.from({length:total},(_,index)=>{const id=index+1;const tireNumber=Number(vehicle.id)*10+id;return{id,code:`P${id}`,side:id%2?'Lado izquierdo':'Lado derecho',tire:`LL-${String(tireNumber).padStart(5,'0')}`,state:'normal',outer:null,center:null,inner:null,condition:'',cause:'',recommendation:'',notes:''}})}
}
