import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DiagramAxle, DiagramPosition, VehicleAxleDiagram } from '../../shared/vehicle-axle-diagram';

@Component({selector:'app-movements-page',imports:[FormsModule,VehicleAxleDiagram],template:`
<section class="page"><header><p class="eyebrow">Operación transaccional</p><h1>Movimientos de llantas</h1><p>Selecciona origen y destino. Ninguna llanta será reemplazada sin indicar qué hacer con ella.</p></header>
<div class="flow"><section class="panel"><h2>1. Vehículo y origen</h2><label>Vehículo<select [(ngModel)]="vehicle"><option>Interno 1542 - ABC123</option></select></label><app-vehicle-axle-diagram [axles]="axles" [selectedId]="origin()?.id||null" vehicleType="Tractocamión" (positionSelected)="selectPosition($event)"/></section>
<section class="panel form"><h2>2. Destino y consecuencias</h2>@if(!origin()){<div class="empty">Selecciona la posición que contiene la llanta.</div>}@else{<div class="selection"><span>ORIGEN</span><b>{{origin()?.code}} → {{origin()?.tire}}</b></div><label>Destino<select [(ngModel)]="destination"><option value="P5">P5 · Posición del vehículo</option><option>Inventario</option><option>Reparación</option><option>Reencauche</option><option>Disposición final</option><option>Otro centro</option></select></label>@if(destination==='P5'){<div class="warning"><b>P5 contiene LL-00456</b><p>Selecciona el destino de la llanta ocupante.</p><select [(ngModel)]="displacedDestination"><option value="">Destino obligatorio</option><option>Inventario</option><option>Reparación</option><option>Reencauche</option><option>Disposición final</option><option>Mover a otra posición</option></select></div>}<label>Motivo<textarea [(ngModel)]="reason" rows="3"></textarea></label><div class="summary"><b>Resumen antes de confirmar</b><span>{{origin()?.tire}}: {{origin()?.code}} → {{destination}}</span>@if(destination==='P5'){<span>LL-00456: P5 → {{displacedDestination||'Destino pendiente'}}</span>}</div><button class="primary" [disabled]="destination==='P5'&&!displacedDestination" (click)="confirm()">Confirmar movimiento</button>}</section></div>
@if(message()){<div class="success">✓ {{message()}}</div>}</section>`,styles:[`
header{margin-bottom:1.3rem}header p{color:#6f838c}.flow{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.panel{padding:1.2rem}.panel h2{font-size:1rem;color:#0b4a78}label{display:block;font-size:.7rem;font-weight:800;color:#597381;margin-bottom:1rem}select,textarea{width:100%;padding:.7rem;border:1px solid #ccdce3;border-radius:9px;margin-top:.35rem;background:white}.empty{padding:3rem 1rem;text-align:center;color:#78909a}.selection,.summary{display:grid;background:#eef5f7;padding:.8rem;border-radius:10px;margin-bottom:1rem}.selection span{font-size:.55rem;color:#748994}.warning{background:#fff4df;border-left:4px solid #f0b429;padding:.8rem;border-radius:8px;margin-bottom:1rem}.warning p{font-size:.7rem}.summary{gap:.35rem;font-size:.72rem}.primary{width:100%}.primary:disabled{opacity:.45}.success{margin-top:1rem;background:#eaf5df;padding:1rem;border-radius:10px;color:#4f771d;font-weight:800}@media(max-width:850px){.flow{grid-template-columns:1fr}}
`]})
export class MovementsPage{vehicle='Interno 1542 - ABC123';destination='P5';displacedDestination='';reason='Rotación preventiva';origin=signal<DiagramPosition|null>(null);message=signal('');axles:DiagramAxle[]=[{id:1,name:'EJE 1',type:'Direccional',positions:[p(1,'P1','Izquierda','LL-00121'),p(2,'P2','Derecha','LL-00122')]},{id:2,name:'EJE 2',type:'Tracción',positions:[p(3,'P3','Izq. externa','LL-00123'),p(4,'P4','Izq. interna','LL-00124'),p(5,'P5','Der. interna','LL-00456'),p(6,'P6','Der. externa','LL-00126')]},{id:3,name:'EJE 3',type:'Tracción',positions:[p(7,'P7','Izq. externa','LL-00127'),p(8,'P8','Izq. interna','LL-00128'),p(9,'P9','Der. interna','LL-00129'),p(10,'P10','Der. externa','LL-00130')]}];selectPosition(x:DiagramPosition){this.origin.set(x);this.message.set('')}confirm(){this.message.set(`Movimiento registrado con trazabilidad. ${this.origin()?.tire} se moverá a ${this.destination}.`)}}
function p(id:number,code:string,side:string,tire:string):DiagramPosition{return{id,code,side,tire,state:id===5?'alert':'normal'}}
