import {CommonModule} from '@angular/common';
import {HttpClient,HttpParams} from '@angular/common/http';
import {Component,OnInit,computed,inject,signal} from '@angular/core';
import {RouterLink} from '@angular/router';
import {firstValueFrom} from 'rxjs';
import {AuthService} from '../../core/auth/auth.service';
import {CatalogsApi} from '../../core/services/catalogs-api';
import {DataTableToolbar,TableColumn,TableFilter} from '../../shared/data-table-toolbar';
interface Move{id:string;numero:string;fecha:string;tipo:string;llantaId:string;llanta:string;serial:string;origen:string;destino:string;vehiculoPosicion:string;centro:string;kilometrajeVehiculo:number|null;kilometrosTramo:number|null;usuario:string;actividadProgramadaId:string|null;motivo:string;observaciones:string|null;estado:string}
interface Page<T>{items:T[];pageNumber:number;pageSize:number;totalItems:number;totalPages:number}
interface Request{id:string;tipo:string;estado:string;centroId:string;centro:string;llantaId:string;llanta:string;posicionOrigenId:string|null;posicionDestinoId:string|null;tipoDestino:string;centroDestinoId:string|null;motivo:string;observaciones:string|null;solicitante:string;aprobador:string|null;motivoRechazo:string|null;fecha:string;fechaRecepcionDestino:string|null}
@Component({selector:'app-movement-ledger',imports:[CommonModule,RouterLink,DataTableToolbar],templateUrl:'./movement-ledger-page.html',styleUrl:'./movement-ledger-page.scss'})
export class MovementLedgerPage implements OnInit{
 private http=inject(HttpClient);private catalogs=inject(CatalogsApi);readonly auth=inject(AuthService);moves=signal<Move[]>([]);requests=signal<Request[]>([]);centers=signal<{id:string;nombre:string}[]>([]);loading=signal(true);message=signal('');tab=signal<'moves'|'requests'|'transfers'|'approvals'>('moves');selected=signal<Move|null>(null);page=signal(1);total=signal(0);search='';filterValues:Record<string,unknown>={};sortBy='fecha';
 readonly columns:TableColumn[]=[{key:'fecha',label:'Fecha',required:true},{key:'numero',label:'Número'},{key:'tipo',label:'Tipo',required:true},{key:'motivo',label:'Motivo'},{key:'llanta',label:'Llanta',required:true},{key:'vehiculo',label:'Vehículo / posición'},{key:'ruta',label:'Origen / destino',required:true},{key:'centro',label:'Centro'},{key:'usuario',label:'Usuario'},{key:'estado',label:'Estado'},{key:'acciones',label:'Acciones',required:true}];
 visibleColumns=this.columns.map(x=>x.key);
 readonly filters=computed<TableFilter[]>(()=>[{key:'fecha',label:'Rango de fechas',type:'date-range'},{key:'numero',label:'Número de movimiento',type:'text'},{key:'tipo',label:'Tipo de movimiento',type:'select',options:[...new Set(this.moves().map(x=>x.tipo))].map(x=>({value:x,label:x}))},{key:'centroId',label:'Centro',type:'select',options:this.centers().map(x=>({value:x.id,label:x.nombre}))},{key:'usuario',label:'Usuario / técnico',type:'text'},{key:'origen',label:'Origen',type:'text'},{key:'destino',label:'Destino',type:'text'}]);
 readonly visibleRequests=computed(()=>this.requests().filter(x=>this.tab()==='transfers'?!!x.centroDestinoId:this.tab()==='approvals'?x.estado==='PENDIENTE_APROBACION':true));
 async ngOnInit(){await this.refresh()}
 async refresh(page=1){this.loading.set(true);this.message.set('');try{const params=this.params(page);const calls:any[]=[firstValueFrom(this.http.get<Page<Move>>('/api/operaciones/movimientos',{params}))];if(!this.centers().length)calls.push(firstValueFrom(this.catalogs.all('centros',true)),firstValueFrom(this.http.get<Request[]>('/api/operaciones/solicitudes')));const result=await Promise.all(calls);const data=result[0] as Page<Move>;this.moves.set(data.items);this.page.set(data.pageNumber);this.total.set(data.totalItems);if(result[1])this.centers.set(result[1]);if(result[2])this.requests.set(result[2]);}catch(e:any){this.message.set(e?.userMessage??'No fue posible cargar la trazabilidad.')}finally{this.loading.set(false)}}
 private params(page:number){let p=new HttpParams().set('pagina',page).set('tamano',20);if(this.search.trim())p=p.set('buscar',this.search.trim());const map:Record<string,string>={numero:'numero',tipo:'tipo',centroId:'centroId',usuario:'usuario',origen:'origen',destino:'destino',fechaMin:'desde',fechaMax:'hasta'};for(const[k,v]of Object.entries(map)){const value=this.filterValues[k];if(value!==''&&value!=null)p=p.set(v,String(value))}return p}
 show(key:string){return this.visibleColumns.includes(key)} clear(){this.search='';this.filterValues={};void this.refresh(1)} apply(){void this.refresh(1)}
 async resolve(x:Request,approve:boolean){const motivo=approve?'':prompt('Motivo obligatorio del rechazo:')?.trim();if(!approve&&!motivo)return;try{await firstValueFrom(this.http.post(`/api/operaciones/solicitudes/${x.id}/resolver`,{aprobar:approve,motivo}));await this.refresh(this.page())}catch(e:any){this.message.set(e?.userMessage??'No fue posible resolver la solicitud.')}}
 async receive(x:Request){try{await firstValueFrom(this.http.post(`/api/operaciones/solicitudes/${x.id}/recibir`,{}));await this.refresh(this.page())}catch(e:any){this.message.set(e?.userMessage??'No fue posible recibir el traslado.')}}
}
