import {CommonModule} from '@angular/common';
import {HttpClient} from '@angular/common/http';
import {Component,OnInit,computed,inject,signal} from '@angular/core';
import {firstValueFrom} from 'rxjs';
import {AuthService} from '../../core/auth/auth.service';
import {CatalogsApi} from '../../core/services/catalogs-api';
import {DataTableToolbar,TableFilter} from '../../shared/data-table-toolbar';
interface Move{id:string;numero:string;fecha:string;tipo:string;llantaId:string;llanta:string;serial:string;origen:string;destino:string;vehiculoPosicion:string;centro:string;kilometrajeVehiculo:number|null;kilometrosTramo:number|null;usuario:string;actividadProgramadaId:string|null;motivo:string;observaciones:string|null;estado:string}
interface Request{id:string;tipo:string;estado:string;centroId:string;centro:string;llantaId:string;llanta:string;posicionOrigenId:string|null;posicionDestinoId:string|null;tipoDestino:string;centroDestinoId:string|null;motivo:string;observaciones:string|null;solicitante:string;aprobador:string|null;motivoRechazo:string|null;fecha:string;fechaRecepcionDestino:string|null}
@Component({selector:'app-movement-ledger',imports:[CommonModule,DataTableToolbar],templateUrl:'./movement-ledger-page.html',styleUrl:'./movement-ledger-page.scss'})
export class MovementLedgerPage implements OnInit{private http=inject(HttpClient);private catalogs=inject(CatalogsApi);readonly auth=inject(AuthService);moves=signal<Move[]>([]);requests=signal<Request[]>([]);centers=signal<{id:string;nombre:string}[]>([]);loading=signal(true);message=signal('');tab=signal<'moves'|'requests'|'transfers'|'approvals'>('moves');search='';filterValues:Record<string,unknown>={};sortBy='fecha';
 readonly filters=computed<TableFilter[]>(()=>[{key:'centers',label:'Centro',type:'multi',options:this.centers().map(x=>({value:x.nombre,label:x.nombre}))},{key:'types',label:'Tipo',type:'multi',options:[...new Set(this.moves().map(x=>x.tipo))].map(x=>({value:x,label:x}))},{key:'states',label:'Estado',type:'multi',options:[{value:'EJECUTADO',label:'Ejecutado'},{value:'PENDIENTE_APROBACION',label:'Pendiente aprobación'},{value:'APROBADO',label:'Aprobado'},{value:'RECHAZADO',label:'Rechazado'}]},{key:'users',label:'Usuario',type:'multi',options:[...new Set(this.moves().map(x=>x.usuario))].map(x=>({value:x,label:x}))},{key:'fecha',label:'Fecha',type:'range'}]);
 readonly visibleMoves=computed(()=>this.moves().filter(x=>{const q=this.search.toLowerCase(),f=this.filterValues;const match=(k:string,v:string)=>!(f[k] as string[]|undefined)?.length||(f[k] as string[]).includes(v);return(!q||[x.llanta,x.serial,x.vehiculoPosicion].some(v=>v.toLowerCase().includes(q)))&&match('centers',x.centro)&&match('types',x.tipo)&&match('states',x.estado)&&match('users',x.usuario)}));readonly visibleRequests=computed(()=>this.requests().filter(x=>this.tab()==='transfers'?!!x.centroDestinoId:this.tab()==='approvals'?x.estado==='PENDIENTE_APROBACION':true));
 async ngOnInit(){await this.refresh()} async refresh(){this.loading.set(true);try{const[m,r,c]=await Promise.all([firstValueFrom(this.http.get<Move[]>('/api/operaciones/movimientos')),firstValueFrom(this.http.get<Request[]>('/api/operaciones/solicitudes')),firstValueFrom(this.catalogs.all('centros',true))]);this.moves.set(m);this.requests.set(r);this.centers.set(c);this.loading.set(false)}catch(e:any){this.message.set(e?.userMessage??'No fue posible cargar la trazabilidad.');this.loading.set(false)}} clear(){this.search='';this.filterValues={}} apply(){this.filterValues={...this.filterValues}} async resolve(x:Request,approve:boolean){const motivo=approve?'':prompt('Motivo obligatorio del rechazo:')?.trim();if(!approve&&!motivo)return;try{await firstValueFrom(this.http.post(`/api/operaciones/solicitudes/${x.id}/resolver`,{aprobar:approve,motivo}));await this.refresh()}catch(e:any){this.message.set(e?.userMessage??'No fue posible resolver la solicitud.')}}async receive(x:Request){try{await firstValueFrom(this.http.post(`/api/operaciones/solicitudes/${x.id}/recibir`,{}));await this.refresh()}catch(e:any){this.message.set(e?.userMessage??'No fue posible recibir el traslado.')}}}
