export interface Page<T> { items:T[]; pageNumber:number; pageSize:number; totalItems:number; totalPages:number; }
export interface CatalogItem { id:string; codigo:string; nombre:string; activo:boolean; padreId?:string|null; padreNombre?:string|null; }
export interface Tire { id:string; codigo:string; serial:string; marca:string; referencia:string; dimension:string; tipo:string; estado:string; centro:string; ubicacionActual:string; profundidadInicial:number; kilometrajeAcumulado:number; numeroReencauches:number; vehiculoActual:string|null; posicionActual:string|null; ultimaInspeccion:string|null;ultimaProfundidadMinima:number|null;numeroReparaciones:number;numeroMontajes:number;atencion:string; activo:boolean; rowVersion:string; }
export interface TireLifeEvent {fecha:string;tipo:string;descripcion:string;usuario:string;centro:string|null;vehiculo:string|null;posicion:string|null;kilometraje:number|null;recorrido:number|null}
export interface TireMount{fechaInicio:string;fechaFin:string|null;vehiculo:string;placa:string;posicion:string;kilometrajeMontaje:number|null;kilometrajeDesmontaje:number|null;recorrido:number|null;actual:boolean}
export interface TireInspection{id:string;fecha:string;vehiculo:string;placa:string;posicion:string;centro:string;exterior:number|null;centroProfundidad:number|null;interior:number|null;minima:number|null;estado:string}
export interface TireService{id:string;tipo:string;estado:string;fecha:string;proveedor:string|null;motivo:string;fechaEnvio:string|null;fechaRetorno:string|null}
export interface TireMovement{id:string;fecha:string;tipo:string;motivo:string;centro:string;usuario:string;posicionOrigen:string|null;posicionDestino:string|null}
export interface TireDetail {llanta:Tire;resumen:{fechaIngreso:string;montajes:number;reparaciones:number;reencauches:number;ultimaReparacion:string|null;ultimoReencauche:string|null};montajes:TireMount[];inspecciones:TireInspection[];servicios:TireService[];movimientos:TireMovement[];historial:TireLifeEvent[];requiereConciliacion:boolean}
export interface TireMetrics{total:number;montadas:number;disponibles:number;reparacion:number;reencauche:number;requierenAtencion:number}
export interface TireInput { codigo:string; serial:string; marcaId:string; referenciaId:string; dimensionId:string; tipoLlantaId:string; estadoLlantaId:string; centroId:string; ubicacionActual:string; fechaCompra:string|null; costo:number|null; profundidadInicial:number; fechaIngreso:string|null; observaciones:string|null; rowVersion?:string; }
