import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { Schedule, SchedulingApi, Technician } from '../scheduling/scheduling-api';
import { ActivitiesApi, Activity } from './activities-api';
type Row=Schedule;
@Component({selector:'app-activities-page',imports:[FormsModule],templateUrl:'./activities-page.html',styleUrl:'./activities-page.scss'})
export class ActivitiesPage implements OnInit{
 private personalApi=inject(ActivitiesApi);private schedulingApi=inject(SchedulingApi);private router=inject(Router);readonly auth=inject(AuthService);
 rows=signal<Row[]>([]);technicians=signal<Technician[]>([]);loading=signal(true);error=signal('');busy=signal('');view=signal<'list'|'calendar'>((sessionStorage.getItem('activities_view') as 'list'|'calendar')||'list');period=signal<'month'|'week'>('month');anchor=signal(new Date());selected=signal<Row|null>(null);filters={centroId:'',tecnicoUsuarioId:'',estado:'',prioridad:'',tipo:'',fecha:''};quick=signal('');
 isTech=computed(()=>this.auth.user()?.role==='TECNICO');centers=computed(()=>[...new Map(this.rows().map(x=>[x.centroId,{id:x.centroId,nombre:x.centro}])).values()].sort((a,b)=>a.nombre.localeCompare(b.nombre)));types=computed(()=>[...new Set(this.rows().map(x=>x.tipo))].sort());
 visible=computed(()=>this.rows().filter(x=>(!this.filters.centroId||x.centroId===this.filters.centroId)&&(!this.filters.tecnicoUsuarioId||x.tecnicoUsuarioId===this.filters.tecnicoUsuarioId)&&(!this.filters.estado||x.estado===this.filters.estado)&&(!this.filters.prioridad||x.prioridad===this.filters.prioridad)&&(!this.filters.tipo||x.tipo===this.filters.tipo)&&(!this.filters.fecha||this.isoDay(x.inicio)===this.filters.fecha)));
 metrics=computed(()=>{const today=this.isoDay(new Date());return{pending:this.rows().filter(x=>x.estado==='Pendiente').length,running:this.rows().filter(x=>x.estado==='EnEjecucion').length,overdue:this.rows().filter(x=>x.estado==='Vencida').length,done:this.rows().filter(x=>x.fechaCumplimiento&&this.isoDay(x.fechaCumplimiento)===today).length}});attention=computed(()=>this.isTech()?[]:this.rows().filter(x=>x.estado==='Vencida'||(['Alta','Crítica'].includes(x.prioridad)&&x.estado==='Pendiente')).slice(0,6));
 days=computed(()=>{const a=new Date(this.anchor()),start=new Date(a),count=this.period()==='week'?7:42;if(this.period()==='month'){start.setDate(1);start.setDate(start.getDate()-((start.getDay()+6)%7))}else start.setDate(start.getDate()-((start.getDay()+6)%7));return Array.from({length:count},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return{date,key:this.isoDay(date),current:date.getMonth()===a.getMonth(),items:this.visible().filter(x=>this.isoDay(x.inicio)===this.isoDay(date))}})});
 async ngOnInit(){await this.load()} async load(){this.loading.set(true);this.error.set('');try{if(this.isTech()){this.rows.set((await firstValueFrom(this.personalApi.list())).map(x=>this.personal(x)))}else{const [rows,techs]=await Promise.all([firstValueFrom(this.schedulingApi.list(this.serverFilters())),firstValueFrom(this.schedulingApi.technicians())]);this.rows.set(rows);this.technicians.set(techs)}}catch{this.error.set('No fue posible cargar las actividades desde el servidor.')}finally{this.loading.set(false)}}
 async apply(){if(!this.isTech())await this.load()} setView(v:'list'|'calendar'){this.view.set(v);sessionStorage.setItem('activities_view',v)} setQuick(value:string){this.quick.set(value);this.filters.estado='';this.filters.fecha='';if(value==='today')this.filters.fecha=this.isoDay(new Date());else if(value==='overdue')this.filters.estado='Vencida';else if(value==='done')this.filters.estado='Cumplida';else if(value==='upcoming')this.filters.estado='Pendiente';void this.apply()}
 serverFilters(){const f:Record<string,string>={...this.filters};delete f['fecha'];if(this.filters.fecha){f['desde']=new Date(this.filters.fecha+'T00:00:00').toISOString();f['hasta']=new Date(this.filters.fecha+'T23:59:59').toISOString()}return f}
 async act(x:Row){if(!this.isTech()||['Cumplida','Cancelada'].includes(x.estado))return;if(x.estado==='EnEjecucion'){await this.router.navigateByUrl(x.rutaInicio);return}this.busy.set(x.id);try{const updated=await firstValueFrom(this.personalApi.start(x.id));this.replace(updated);await this.router.navigateByUrl(updated.rutaInicio)}catch{this.error.set('No fue posible iniciar la actividad.')}finally{this.busy.set('')}}
 async complete(x:Row){if(!confirm('¿Confirmas que deseas marcar esta actividad como cumplida?'))return;this.busy.set(x.id);try{this.replace(await firstValueFrom(this.personalApi.complete(x.id)));this.selected.set(null)}catch{this.error.set('No fue posible completar la actividad.')}finally{this.busy.set('')}}
 replace(a:Activity){const row=this.personal(a);this.rows.update(all=>all.map(x=>x.id===row.id?row:x))} personal(a:Activity):Row{return{id:a.id,tipo:a.tipo,inicio:a.fecha,fin:null,centroId:a.centro,centro:a.centro,vehiculoId:a.vehiculoId,vehiculo:a.vehiculo,tecnicoUsuarioId:null,tecnico:this.auth.user()?.username??'',tecnicoNombre:this.auth.user()?.name??'',prioridad:a.prioridad,estado:a.estado,rutaInicio:a.rutaInicio,tieneSolapamiento:false,observaciones:null,motivoCancelacion:null,fechaCumplimiento:a.fechaCumplimiento,rowVersion:''}}
 move(delta:number){const d=new Date(this.anchor());this.period()==='month'?d.setMonth(d.getMonth()+delta):d.setDate(d.getDate()+delta*7);this.anchor.set(d)} today(){this.anchor.set(new Date())} date(v:string|Date){return new Intl.DateTimeFormat('es-CO',{weekday:'short',day:'2-digit',month:'short'}).format(new Date(v))} time(v:string){return new Intl.DateTimeFormat('es-CO',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v))} month(){return new Intl.DateTimeFormat('es-CO',{month:'long',year:'numeric'}).format(this.anchor())} isoDay(v:string|Date){const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
}
