import { Component, inject, signal } from '@angular/core';
import { Router } from '@angular/router';

interface Activity{id:string;type:string;date:string;time:string;center:string;vehicle:string;priority:string;state:string;route:string}
@Component({selector:'app-activities-page',template:`
<section class="page"><header><div><p class="eyebrow">Agenda del técnico</p><h1>Mis actividades</h1><p>Todo tu trabajo programado, listo para iniciar sin volver a buscar el vehículo.</p></div><span>{{pending()}} pendientes</span></header>
<div class="filters"><button class="active">Hoy</button><button>Próximas</button><button>Completadas</button></div>
<div class="activities">@for(a of activities;track a.id){<article [class.high]="a.priority==='Alta'"><div class="date"><b>{{a.time}}</b><small>{{a.date}}</small></div><div class="info"><span>{{a.type}}</span><h2>{{a.vehicle}}</h2><p>{{a.center}} · Prioridad {{a.priority}}</p></div><span class="status">{{a.state}}</span><button (click)="start(a)">INICIAR {{a.type.toUpperCase()}}</button></article>}</div>
</section>`,styles:[`
header{display:flex;justify-content:space-between;align-items:end;margin-bottom:1.5rem}header p{color:#6b808b}header>span{background:#eaf4dd;color:#50791c;padding:.55rem .8rem;border-radius:99px;font-weight:800}.filters{display:flex;gap:.4rem;margin-bottom:1rem}.filters button{border:0;border-radius:9px;padding:.65rem 1rem;font-weight:800;color:#567080}.filters .active{background:#0b4a78;color:#fff}.activities{display:grid;gap:.8rem}.activities article{display:grid;grid-template-columns:90px 1fr auto auto;align-items:center;gap:1rem;background:white;border:1px solid #dce7eb;border-left:5px solid #79ad38;border-radius:14px;padding:1rem}.activities article.high{border-left-color:#e15b35}.date{display:grid;text-align:center;border-right:1px solid #e2eaed}.date b{font-size:1.25rem;color:#0b4a78}.date small,.info p{color:#748791}.info span{font-size:.62rem;text-transform:uppercase;font-weight:900;color:#719d39}.info h2{margin:.15rem 0;font-size:1rem}.info p{margin:0;font-size:.7rem}.status{font-size:.65rem;background:#eef4f6;padding:.35rem .55rem;border-radius:99px}.activities button{border:0;background:#0b4a78;color:white;padding:.7rem;border-radius:9px;font-weight:800}@media(max-width:700px){header{display:grid}.activities article{grid-template-columns:65px 1fr}.activities button{grid-column:1/-1}.status{justify-self:start}}
`]})
export class ActivitiesPage{private router=inject(Router);activities:Activity[]=[{id:'ACT-101',type:'Inspección',date:'Hoy',time:'08:00',center:'EDINSA Medellín',vehicle:'Interno 1542 - ABC123',priority:'Alta',state:'Pendiente',route:'/inspecciones?actividadId=ACT-101&vehiculo=1542'},{id:'ACT-102',type:'Montaje',date:'Hoy',time:'10:30',center:'POSTOBON Bello',vehicle:'Interno 2450 - JKL908',priority:'Media',state:'Pendiente',route:'/montajes?actividadId=ACT-102&vehiculo=2450'},{id:'ACT-103',type:'Revisión',date:'Hoy',time:'14:00',center:'EDINSA Medellín',vehicle:'Interno 3190 - MNO317',priority:'Media',state:'Pendiente',route:'/inspecciones?actividadId=ACT-103&vehiculo=3190'}];pending=signal(this.activities.length);start(a:Activity){a.state='En ejecución';void this.router.navigateByUrl(a.route)}}
