import { Component, OnInit, computed, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { AuthService } from '../../core/auth/auth.service';
import { ActivitiesApi, Activity } from '../activities/activities-api';

@Component({selector:'app-dashboard',imports:[RouterLink],template:`
@if(auth.user()?.role==='TECNICO'){
<main class="page"><header class="head"><div><p class="eyebrow">Resumen del técnico</p><h1>Hola, {{firstName()}}</h1><p>Tu trabajo asignado desde la programación operativa.</p></div><a routerLink="/mis-actividades">Ver agenda completa →</a></header>
@if(loading()){<div class="notice">Cargando resumen desde el servidor…</div>}@else if(error()){<div class="notice error" role="alert">{{error()}} <button (click)="load()">Reintentar</button></div>}@else{
<section class="metrics" aria-label="Resumen de actividades"><article><span>PENDIENTES</span><b>{{pending()}}</b><small>Actividades asignadas</small></article><article><span>EN EJECUCIÓN</span><b>{{running()}}</b><small>Actividades iniciadas</small></article><article><span>CENTROS</span><b>{{centers()}}</b><small>Ubicaciones en la agenda</small></article></section>
<section class="agenda"><header><div><p class="eyebrow">Agenda</p><h2>Próximas actividades</h2></div><span>{{activities().length}} asignadas</span></header>@if(!activities().length){<p class="empty">No tienes actividades asignadas.</p>}@else{@for(a of activities().slice(0,3);track a.id){<article><time><b>{{time(a.fecha)}}</b><small>{{day(a.fecha)}}</small></time><div><span>{{a.tipo}}</span><h3>{{a.vehiculo}}</h3><p>{{a.centro}} · Prioridad {{a.prioridad}}</p></div><span class="state">{{a.estado}}</span><a [attr.href]="a.rutaInicio" (click)="open($event,a.rutaInicio)">Abrir →</a></article>}}</section>}
</main>
}@else{
<section class="hero page"><div><p class="eyebrow">GLLD · EDINSA</p><h1>Cada llanta.<br><em>Toda su historia.</em></h1><p>Gestión logística de llantas para la operación de transporte de Postobón.</p><a routerLink="/llantas">Abrir inventario →</a></div><div class="wheel" aria-hidden="true"><span></span></div></section>
}`,styles:[`
.head{display:flex;justify-content:space-between;align-items:end;margin-bottom:1.2rem}.head h1{margin:.15rem 0;color:#123f5c}.head p:last-child{color:#6b808b}.head a,.agenda a{color:#0b4a78;font-weight:800;text-decoration:none}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-bottom:1rem}.metrics article{display:grid;gap:.25rem;padding:1.1rem;background:white;border:1px solid #dce7eb;border-top:4px solid #8bc53f;border-radius:14px}.metrics span{font-size:.62rem;letter-spacing:.1em;font-weight:900;color:#6e8791}.metrics b{font-size:1.8rem;color:#123f5c}.metrics small{color:#71858e}.agenda{padding:1.2rem;background:white;border:1px solid #dce7eb;border-radius:16px}.agenda>header{display:flex;justify-content:space-between;align-items:end}.agenda h2{margin:.1rem 0 1rem}.agenda>header>span,.state{font-size:.65rem;background:#eef4f6;padding:.35rem .55rem;border-radius:99px}.agenda article{display:grid;grid-template-columns:75px 1fr auto auto;align-items:center;gap:1rem;padding:.8rem;border-top:1px solid #e4ecef}.agenda time{display:grid;text-align:center}.agenda time b{color:#0b4a78}.agenda time small,.agenda p{color:#748791}.agenda article div>span{font-size:.62rem;text-transform:uppercase;font-weight:900;color:#719d39}.agenda h3{margin:.1rem 0;font-size:.95rem}.agenda p{margin:0;font-size:.7rem}.notice,.empty{padding:2rem;text-align:center;background:#fff;border:1px solid #dce7eb;border-radius:14px;color:#657b86}.notice.error{color:#9d3d28}.notice button{margin-left:.5rem}.hero{min-height:66vh;display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:3rem;background:radial-gradient(circle at 90% 10%,#d6e7df 0,transparent 40%)}h1 em{color:#a67a00;font-style:normal}.hero p:not(.eyebrow){max-width:570px;font-size:1.15rem;color:#617571}.hero a{display:inline-block;margin-top:1rem;color:#183a36;font-weight:800;text-decoration:none;border-bottom:3px solid #e0b72c;padding-bottom:.2rem}.wheel{width:min(35vw,420px);aspect-ratio:1;border-radius:50%;background:repeating-conic-gradient(#1b2d2b 0 5deg,#314542 5deg 9deg);padding:55px;box-shadow:20px 30px 70px #16352c33;transform:rotate(-12deg)}.wheel span{display:block;width:100%;height:100%;border:30px solid #9daaa6;border-radius:50%;background:radial-gradient(circle,#172a28 0 13%,#d8dedb 14% 38%,#253a37 39%)}@media(max-width:760px){.head{display:grid;gap:.6rem}.metrics{grid-template-columns:1fr}.agenda article{grid-template-columns:60px 1fr}.agenda article>a{grid-column:1/-1}.state{justify-self:start}.hero{grid-template-columns:1fr}.wheel{display:none}}
`]})
export class Dashboard implements OnInit{
 readonly auth=inject(AuthService);private readonly api=inject(ActivitiesApi);private readonly router=inject(Router);activities=signal<Activity[]>([]);loading=signal(true);error=signal('');
 pending=computed(()=>this.activities().filter(a=>a.estado==='Pendiente'||a.estado==='Vencida').length);running=computed(()=>this.activities().filter(a=>a.estado==='EnEjecucion'||a.estado==='En ejecución').length);centers=computed(()=>new Set(this.activities().map(a=>a.centro)).size);
 ngOnInit(){if(this.auth.user()?.role==='TECNICO')void this.load();else this.loading.set(false)}
 async load(){this.loading.set(true);this.error.set('');try{this.activities.set(await firstValueFrom(this.api.list()))}catch{this.error.set('No fue posible cargar el resumen operativo.')}finally{this.loading.set(false)}}
 firstName(){return this.auth.user()?.name.split(' ')[0]??'Técnico'}
 open(event:Event,url:string){event.preventDefault();void this.router.navigateByUrl(url)}
 time(value:string){return new Intl.DateTimeFormat('es-CO',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))}day(value:string){return new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short'}).format(new Date(value))}
}
