using System.Globalization;
using System.Text;
using System.Text.Json;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic.FileIO;
using SistemaLlantas.Api.Security;
using SistemaLlantas.Application.Common;
using SistemaLlantas.Application.Vehiculos;
using SistemaLlantas.Domain.Entities;
using SistemaLlantas.Infrastructure.Persistence;

namespace SistemaLlantas.Api.Controllers;

[ApiController,Route("api/carga-masiva"),Authorize(Policy="CargaMasiva.Importar")]
public sealed class CargaMasivaController(LlantasDbContext db,IVehiculoService vehiculos):ControllerBase
{
 private static readonly string[] TireColumns=["CodigoLlanta","Serial","Marca","Referencia","Dimension","TipoLlanta","Estado","Centro","Ubicacion","ProfundidadInicial"];
 private static readonly string[] VehicleColumns=["Interno","Placa","Centro","TipoVehiculo","ConfiguracionEjes","Kilometraje","Estado"];
 [HttpGet("plantillas")]public object Plantillas()=>new[]{new{tipo="llantas",columnas=TireColumns},new{tipo="vehiculos",columnas=VehicleColumns}};
 [HttpGet("plantillas/{tipo}")]public IActionResult Plantilla(string tipo,[FromQuery]string formato="xlsx"){var cols=Columns(tipo);if(formato.Equals("csv",StringComparison.OrdinalIgnoreCase))return File(Encoding.UTF8.GetBytes(string.Join(',',cols)+Environment.NewLine),"text/csv",$"plantilla-{tipo}.csv");using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Plantilla");for(var i=0;i<cols.Length;i++)ws.Cell(1,i+1).Value=cols[i];ws.Row(1).Style.Font.Bold=true;ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return File(ms.ToArray(),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",$"plantilla-{tipo}.xlsx");}
 [HttpPost("previsualizar"),RequestSizeLimit(26_000_000)]public async Task<ActionResult<PreviewDto>> Preview([FromForm]string tipo,[FromForm]IFormFile archivo,CancellationToken ct){if(archivo.Length is 0 or >25_000_000)throw new ValidacionException("El archivo está vacío o supera 25 MB.");var ext=Path.GetExtension(archivo.FileName).ToLowerInvariant();if(ext is not ".csv" and not ".xlsx")throw new ValidacionException("Sólo se permiten CSV y XLSX.");var rows=await Read(archivo,ext,ct);var required=Columns(tipo);if(rows.Count==0||required.Any(c=>!rows[0].ContainsKey(c)))throw new ValidacionException("La estructura no coincide con la plantilla vigente.");var errors=await Validate(tipo,rows,User.AlcanceCentros(),ct);var invalid=errors.Select(x=>x.Fila).ToHashSet();var valid=rows.Select((x,i)=>(Row:x,Number:i+2)).Where(x=>!invalid.Contains(x.Number)).Select(x=>x.Row).ToList();var load=new CargaMasiva{Tipo=tipo.ToLowerInvariant(),NombreArchivo=Path.GetFileName(archivo.FileName),TotalFilas=rows.Count,FilasValidas=valid.Count,FilasConError=errors.Count,FilasJson=JsonSerializer.Serialize(valid),ErroresJson=JsonSerializer.Serialize(errors),Usuario=User.Username(),UsuarioCreacion=User.Username()};db.CargasMasivas.Add(load);await db.SaveChangesAsync(ct);return new PreviewDto(load.Id,load.TotalFilas,load.FilasValidas,load.FilasConError,errors.Take(100).ToList());}
 [HttpPost("{id:guid}/confirmar")]public async Task<ResultadoDto> Confirm(Guid id,CancellationToken ct){var result=new ResultadoDto(id,0,0);var strategy=db.Database.CreateExecutionStrategy();await strategy.ExecuteAsync(async()=>{await using var tx=await db.Database.BeginTransactionAsync(ct);var load=await db.CargasMasivas.SingleOrDefaultAsync(x=>x.Id==id&&x.Usuario==User.Username()&&x.Estado=="PREVISUALIZADA",ct)??throw new KeyNotFoundException("Previsualización no encontrada o ya procesada.");var rows=JsonSerializer.Deserialize<List<Dictionary<string,string>>>(load.FilasJson)??[];var processed=0;if(load.Tipo=="llantas")processed=await ImportTires(rows,User.AlcanceCentros(),ct);else if(load.Tipo=="vehiculos")processed=await ImportVehicles(rows,User.AlcanceCentros(),ct);else throw new ValidacionException("Tipo de carga no soportado.");load.Estado="PROCESADA";load.FechaProcesamiento=DateTimeOffset.UtcNow;load.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);result=new(load.Id,processed,load.FilasConError);});return result;}
 [HttpGet("{id:guid}/errores")]public async Task<IActionResult> Errors(Guid id,CancellationToken ct){var load=await db.CargasMasivas.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.Usuario==User.Username(),ct)??throw new KeyNotFoundException();var errors=JsonSerializer.Deserialize<List<RowError>>(load.ErroresJson)??[];using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Errores");ws.Cell(1,1).Value="Fila";ws.Cell(1,2).Value="Campo";ws.Cell(1,3).Value="Error";for(var i=0;i<errors.Count;i++){ws.Cell(i+2,1).Value=errors[i].Fila;ws.Cell(i+2,2).Value=errors[i].Campo;ws.Cell(i+2,3).Value=errors[i].Error;}using var ms=new MemoryStream();wb.SaveAs(ms);return File(ms.ToArray(),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",$"errores-{load.NombreArchivo}.xlsx");}
 private async Task<List<RowError>> Validate(string type,List<Dictionary<string,string>> rows,AlcanceCentros scope,CancellationToken ct)
 {
  var errors=new List<RowError>();var isTire=type.Equals("llantas",StringComparison.OrdinalIgnoreCase);
  var centers=await db.Centros.AsNoTracking().Where(x=>x.Activo).ToDictionaryAsync(x=>x.Codigo,StringComparer.OrdinalIgnoreCase,ct);
  var existingTires=isTire?await db.Llantas.IgnoreQueryFilters().Select(x=>x.Codigo).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var existingVehicles=!isTire?await db.Vehiculos.Select(x=>x.NumeroInterno).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var marcas=isTire?await db.Marcas.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.Marcas.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var referencias=isTire?await db.Referencias.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.Referencias.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var dimensiones=isTire?await db.Dimensiones.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.Dimensiones.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var tiposLlanta=isTire?await db.TiposLlanta.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.TiposLlanta.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var estados=isTire?await db.EstadosLlanta.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.EstadosLlanta.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var configs=!isTire?await db.ConfiguracionesVehiculo.Where(x=>x.Activo).Select(x=>x.Codigo).Concat(db.ConfiguracionesVehiculo.Where(x=>x.Activo).Select(x=>x.Nombre)).ToHashSetAsync(StringComparer.OrdinalIgnoreCase,ct):[];
  var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  for(var i=0;i<rows.Count;i++)
  {
   var r=rows[i];var n=i+2;foreach(var c in Columns(type))if(string.IsNullOrWhiteSpace(r.GetValueOrDefault(c)))errors.Add(new(n,c,"Valor obligatorio."));
   var centerCode=r.GetValueOrDefault("Centro")??"";if(!centers.TryGetValue(centerCode,out var center))errors.Add(new(n,"Centro","Centro inexistente o inactivo."));else if(!scope.Autoriza(center.Id))errors.Add(new(n,"Centro","Centro fuera del alcance autorizado."));
   var key=isTire?r.GetValueOrDefault("CodigoLlanta")??"":r.GetValueOrDefault("Interno")??"";if(!seen.Add(key)||existingTires.Contains(key)||existingVehicles.Contains(key))errors.Add(new(n,isTire?"CodigoLlanta":"Interno","Identificador duplicado."));
   if(isTire){if(!decimal.TryParse(r.GetValueOrDefault("ProfundidadInicial"),NumberStyles.Number,CultureInfo.InvariantCulture,out var depth)||depth<0)errors.Add(new(n,"ProfundidadInicial","Número no negativo inválido."));if(!marcas.Contains(r.GetValueOrDefault("Marca")??""))errors.Add(new(n,"Marca","No existe en el catálogo."));if(!referencias.Contains(r.GetValueOrDefault("Referencia")??""))errors.Add(new(n,"Referencia","No existe en el catálogo."));if(!dimensiones.Contains(r.GetValueOrDefault("Dimension")??""))errors.Add(new(n,"Dimension","No existe en el catálogo."));if(!tiposLlanta.Contains(r.GetValueOrDefault("TipoLlanta")??""))errors.Add(new(n,"TipoLlanta","No existe en el catálogo."));if(!estados.Contains(r.GetValueOrDefault("Estado")??""))errors.Add(new(n,"Estado","No existe en el catálogo."));}
   else if(!configs.Contains(r.GetValueOrDefault("ConfiguracionEjes")??""))errors.Add(new(n,"ConfiguracionEjes","No existe una configuración homologada con ese código o nombre."));
  }
  return errors;
 }
 private async Task<int> ImportTires(List<Dictionary<string,string>> rows,AlcanceCentros scope,CancellationToken ct){var count=0;foreach(var r in rows){var center=await db.Centros.SingleAsync(x=>x.Codigo==r["Centro"]&&x.Activo,ct);if(!scope.Autoriza(center.Id))throw new UnauthorizedAccessException();var marca=await db.Marcas.SingleAsync(x=>x.Codigo==r["Marca"]||x.Nombre==r["Marca"],ct);var reference=await db.Referencias.SingleAsync(x=>(x.Codigo==r["Referencia"]||x.Nombre==r["Referencia"])&&x.MarcaId==marca.Id,ct);var dimension=await db.Dimensiones.SingleAsync(x=>x.Codigo==r["Dimension"]||x.Nombre==r["Dimension"],ct);var type=await db.TiposLlanta.SingleAsync(x=>x.Activo&&(x.Codigo==r["TipoLlanta"]||x.Nombre==r["TipoLlanta"]),ct);var state=await db.EstadosLlanta.SingleAsync(x=>x.Codigo==r["Estado"]||x.Nombre==r["Estado"],ct);var tire=new Llanta(r["CodigoLlanta"],r["Serial"]){MarcaId=marca.Id,ReferenciaId=reference.Id,DimensionId=dimension.Id,TipoLlantaId=type.Id,EstadoLlantaId=state.Id,CentroId=center.Id,UbicacionActual=r["Ubicacion"],ProfundidadInicial=decimal.Parse(r["ProfundidadInicial"],CultureInfo.InvariantCulture),UsuarioCreacion=User.Username()};db.Llantas.Add(tire);count++;}await db.SaveChangesAsync(ct);return count;}
 private async Task<int> ImportVehicles(List<Dictionary<string,string>> rows,AlcanceCentros scope,CancellationToken ct){var count=0;foreach(var r in rows){var center=await db.Centros.SingleAsync(x=>x.Codigo==r["Centro"]&&x.Activo,ct);var cfg=await db.ConfiguracionesVehiculo.SingleAsync(x=>x.Codigo==r["ConfiguracionEjes"]||x.Nombre==r["ConfiguracionEjes"],ct);decimal? km=decimal.TryParse(r["Kilometraje"],NumberStyles.Number,CultureInfo.InvariantCulture,out var v)?v:null;await vehiculos.CrearAsync(new(r["Interno"],r["Placa"],r["TipoVehiculo"],center.Id,cfg.Id,km,r["Estado"],null),User.Username(),scope,ct);count++;}return count;}
 private static string[] Columns(string type)=>type.ToLowerInvariant() switch{"llantas"=>TireColumns,"vehiculos"=>VehicleColumns,_=>throw new ValidacionException("Tipo de plantilla no soportado.")};
 private static async Task<List<Dictionary<string,string>>> Read(IFormFile file,string ext,CancellationToken ct){await using var stream=file.OpenReadStream();if(ext==".xlsx"){using var wb=new XLWorkbook(stream);var ws=wb.Worksheets.First();var headers=ws.Row(1).CellsUsed().Select(x=>x.GetString().Trim()).ToList();return ws.RowsUsed().Skip(1).Select(row=>headers.Select((h,i)=>(h,v:row.Cell(i+1).GetFormattedString().Trim())).ToDictionary(x=>x.h,x=>x.v,StringComparer.OrdinalIgnoreCase)).ToList();}using var reader=new StreamReader(stream,Encoding.UTF8,true);var text=await reader.ReadToEndAsync(ct);using var parser=new TextFieldParser(new StringReader(text)){TextFieldType=FieldType.Delimited,HasFieldsEnclosedInQuotes=true};parser.SetDelimiters(",");var headersCsv=parser.ReadFields()??[];var result=new List<Dictionary<string,string>>();while(!parser.EndOfData){var values=parser.ReadFields()??[];result.Add(headersCsv.Select((h,i)=>(h:h.Trim(),v:i<values.Length?values[i].Trim():"")).ToDictionary(x=>x.h,x=>x.v,StringComparer.OrdinalIgnoreCase));}return result;}
 public sealed record RowError(int Fila,string Campo,string Error);public sealed record PreviewDto(Guid Id,int Total,int Validas,int ConError,IReadOnlyList<RowError> Errores);public sealed record ResultadoDto(Guid Id,int Procesadas,int Omitidas);
}
