using System.Security.Cryptography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaLlantas.Api.Security;
using SistemaLlantas.Application.Common;
using SistemaLlantas.Application.Llantas;
using SistemaLlantas.Application.Operaciones;
using SistemaLlantas.Domain.Entities;
using SistemaLlantas.Infrastructure.Persistence;

namespace SistemaLlantas.Api.Controllers;

[ApiController,Route("api/servicios-llanta"),Authorize(Policy="ServiciosLlanta.Consultar")]
public sealed class ServiciosLlantaController(LlantasDbContext db,IOperacionService operaciones,ICicloVidaLlantaService ciclo,IWebHostEnvironment env):ControllerBase
{
 [HttpGet]public async Task<IReadOnlyList<OrdenDto>> Listar([FromQuery]string? tipo,CancellationToken ct){var a=User.AlcanceCentros();var q=db.OrdenesServicioLlanta.AsNoTracking().Where(x=>x.Activo&&(a.VerTodos||a.CentroIds.Contains(x.CentroOrigenId)));if(Enum.TryParse<TipoServicioLlanta>(tipo,true,out var parsed))q=q.Where(x=>x.Tipo==parsed);return await q.OrderByDescending(x=>x.FechaCreacion).Select(x=>new OrdenDto(x.Id,x.Tipo.ToString(),x.Estado,x.LlantaId,x.Llanta.Codigo,x.CentroOrigenId,x.CentroOrigen.Nombre,x.ProveedorId,x.Proveedor!=null?x.Proveedor.Nombre:null,x.Costo,x.Motivo,x.Observaciones,x.Elegible,x.CriterioElegibilidad,x.FechaEnvio,x.FechaRecepcion,x.Evidencias.Count(e=>e.Activo),Convert.ToBase64String(x.RowVersion))).ToListAsync(ct);}
 [HttpGet("proveedores")]public async Task<IReadOnlyList<ProveedorDto>> Proveedores(CancellationToken ct)=>await db.ProveedoresServicio.AsNoTracking().Where(x=>x.Activo).OrderBy(x=>x.Nombre).Select(x=>new ProveedorDto(x.Id,x.Codigo,x.Nombre,x.Tipo)).ToListAsync(ct);
 [HttpPost("proveedores"),Authorize(Policy="Catalogos.Administrar")]public async Task<ProveedorDto> CrearProveedor(ProveedorInput dto,CancellationToken ct){if(string.IsNullOrWhiteSpace(dto.Codigo)||string.IsNullOrWhiteSpace(dto.Nombre))throw new ValidacionException("Código y nombre son obligatorios.");var x=new ProveedorServicio{Codigo=dto.Codigo.Trim().ToUpperInvariant(),Nombre=dto.Nombre.Trim(),Tipo=dto.Tipo.Trim(),UsuarioCreacion=User.Username()};db.ProveedoresServicio.Add(x);await db.SaveChangesAsync(ct);return new(x.Id,x.Codigo,x.Nombre,x.Tipo);}
 [HttpPost,Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<ActionResult<OrdenDto>> Crear(CrearOrdenDto dto,CancellationToken ct){if(!Enum.TryParse<TipoServicioLlanta>(dto.Tipo,true,out var type))throw new ValidacionException("Tipo de servicio inválido.");if(string.IsNullOrWhiteSpace(dto.Motivo))throw new ValidacionException("El motivo es obligatorio.");var a=User.AlcanceCentros();var tire=await db.Llantas.SingleOrDefaultAsync(x=>x.Id==dto.LlantaId&&(a.VerTodos||a.CentroIds.Contains(x.CentroId)),ct)??throw new KeyNotFoundException("Llanta no encontrada.");if(await db.OrdenesServicioLlanta.AnyAsync(x=>x.LlantaId==tire.Id&&x.Activo&&!new[]{"CERRADA","RECHAZADA","NO_REPARABLE","DISPOSICION_FINAL"}.Contains(x.Estado),ct))throw new ConflictoException("La llanta ya tiene un flujo de servicio activo.");var eligible=true;string? criterion=null;if(type==TipoServicioLlanta.Reencauche){var today=DateOnly.FromDateTime(DateTime.UtcNow);var p=await db.ParametrosReencauche.AsNoTracking().Where(x=>x.Activo&&(x.DimensionId==null||x.DimensionId==tire.DimensionId)&&x.VigenteDesde<=today&&(x.VigenteHasta==null||x.VigenteHasta>=today)).OrderByDescending(x=>x.DimensionId.HasValue).FirstOrDefaultAsync(ct);eligible=p is not null&&tire.NumeroReencauches<p.MaximoReencauches;criterion=p is null?"Sin parámetro vigente para la dimensión.":$"Máximo parametrizado: {p.MaximoReencauches}; realizados: {tire.NumeroReencauches}.";}var state=eligible?"PENDIENTE_APROBACION":"NO_ELEGIBLE";var x=new OrdenServicioLlanta{Tipo=type,Estado=state,LlantaId=tire.Id,CentroOrigenId=tire.CentroId,ProveedorId=dto.ProveedorId,Costo=dto.Costo,Motivo=dto.Motivo.Trim(),Observaciones=dto.Observaciones,Elegible=eligible,CriterioElegibilidad=criterion,Solicitante=User.Username(),UsuarioCreacion=User.Username()};db.OrdenesServicioLlanta.Add(x);await db.SaveChangesAsync(ct);return Created(string.Empty,(await Listar(type.ToString(),ct)).Single(y=>y.Id==x.Id));}
 [HttpPost("{id:guid}/aprobar"),Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<OrdenDto> Aprobar(Guid id,CancellationToken ct){var x=await Orden(id,User.AlcanceCentros(),ct);if(x.Estado!="PENDIENTE_APROBACION"||!x.Elegible)throw new ConflictoException("La orden no está pendiente de aprobación o no es elegible.");x.Estado="APROBADA";x.Aprobador=User.Username();x.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);return await Dto(id,User.AlcanceCentros(),ct);}
 [HttpPost("{id:guid}/enviar"),Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<OrdenDto> Enviar(Guid id,CancellationToken ct){var a=User.AlcanceCentros();var x=await Orden(id,a,ct);if(x.Estado!="APROBADA")throw new ConflictoException("La orden debe estar aprobada antes del envío.");if(!x.Elegible)throw new ConflictoException(x.CriterioElegibilidad??"La llanta no es elegible.");if(x.Tipo!=TipoServicioLlanta.DisposicionFinal&&!x.ProveedorId.HasValue)throw new ValidacionException("Seleccione un proveedor del catálogo.");var active=await db.AsignacionesLlantaPosicion.AsNoTracking().SingleOrDefaultAsync(y=>y.LlantaId==x.LlantaId&&y.EsActiva,ct);if(active is not null)throw new ConflictoException("Debe desmontar la llanta antes de enviarla.");if(x.Tipo==TipoServicioLlanta.DisposicionFinal){var r1=await db.Centros.SingleOrDefaultAsync(c=>c.Codigo=="R1"&&c.Activo,ct)??throw new ConflictoException("No existe un centro activo con código R1.");if(x.Llanta.CentroId!=r1.Id){var transferScope=a.VerTodos?a:new(false,a.CentroIds.Append(r1.Id).Distinct().ToArray());await ciclo.TrasladarCentroAsync(x.LlantaId,new(r1.Id,"Traslado para disposición final",x.Observaciones),User.Username(),transferScope,ct);x.Estado="EN_TRANSITO_R1";}else x.Estado="PENDIENTE_DISPOSICION";}else{await operaciones.MoverAsync(new(){LlantaId=x.LlantaId,TipoDestino=x.Tipo==TipoServicioLlanta.Reparacion?"Reparacion":"Reencauche",Motivo=x.Motivo,Observaciones=x.Observaciones},User.Username(),a,ct);x.Estado="ENVIADA";}x.FechaEnvio=DateTimeOffset.UtcNow;x.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);return await Dto(id,User.AlcanceCentros(),ct);}
 [HttpPost("{id:guid}/recibir"),Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<OrdenDto> Recibir(Guid id,CancellationToken ct){var x=await Orden(id,User.AlcanceCentros(),ct);if(x.FechaEnvio is null)throw new ConflictoException("La orden no ha sido enviada.");x.FechaRecepcion=DateTimeOffset.UtcNow;x.Estado=x.Tipo==TipoServicioLlanta.DisposicionFinal?"PENDIENTE_DISPOSICION":"RECIBIDA";x.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);return await Dto(id,User.AlcanceCentros(),ct);}
 [HttpPost("{id:guid}/cerrar"),Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<OrdenDto> Cerrar(Guid id,CerrarOrdenDto dto,CancellationToken ct){var a=User.AlcanceCentros();var x=await Orden(id,a,ct);if(x.FechaRecepcion is null)throw new ConflictoException("Debe registrar la recepción antes de cerrar.");if(!dto.Aceptada){x.Estado=x.Tipo==TipoServicioLlanta.Reparacion?"NO_REPARABLE":"RECHAZADA";}else if(x.Tipo==TipoServicioLlanta.DisposicionFinal){var r1=await db.Centros.AsNoTracking().Where(c=>c.Codigo=="R1"&&c.Activo).Select(c=>(Guid?)c.Id).SingleOrDefaultAsync(ct);if(!r1.HasValue||x.Llanta.CentroId!=r1.Value)throw new ConflictoException("La llanta debe estar recibida físicamente en R1.");if(!x.Evidencias.Any(e=>e.Activo&&e.MimeType.StartsWith("image/")))throw new ValidacionException("La evidencia fotográfica es obligatoria para disposición final.");if(!x.ProveedorId.HasValue)throw new ValidacionException("La empresa receptora es obligatoria.");await operaciones.MoverAsync(new(){LlantaId=x.LlantaId,TipoDestino="DisposicionFinal",Motivo=x.Motivo,Observaciones=dto.Observaciones},User.Username(),a,ct);x.Estado="DISPOSICION_FINAL";}else{await operaciones.MoverAsync(new(){LlantaId=x.LlantaId,TipoDestino="Inventario",Motivo=$"Recepción de {x.Tipo}",Observaciones=dto.Observaciones},User.Username(),a,ct);if(x.Tipo==TipoServicioLlanta.Reencauche)x.Llanta.NumeroReencauches++;x.Estado="CERRADA";}x.Observaciones=dto.Observaciones??x.Observaciones;x.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);return await Dto(id,a,ct);}
 [HttpPost("{id:guid}/evidencias"),Authorize(Policy="ServiciosLlanta.Gestionar"),RequestSizeLimit(10_485_760)]public async Task<ActionResult> Evidencia(Guid id,[FromForm]IFormFile archivo,CancellationToken ct){var x=await Orden(id,User.AlcanceCentros(),ct);if(archivo.Length is 0 or >10_000_000)throw new ValidacionException("Archivo vacío o superior a 10 MB.");var ext=Path.GetExtension(archivo.FileName).ToLowerInvariant();if(ext is not ".jpg" and not ".jpeg" and not ".png" and not ".pdf"||archivo.ContentType is not "image/jpeg" and not "image/png" and not "application/pdf")throw new ValidacionException("Sólo se permiten JPG, PNG y PDF.");await using var source=archivo.OpenReadStream();var signature=new byte[8];var read=await source.ReadAsync(signature,ct);source.Position=0;var jpeg=read>=3&&signature[0]==0xff&&signature[1]==0xd8&&signature[2]==0xff;var png=read>=8&&signature.SequenceEqual(new byte[]{137,80,78,71,13,10,26,10});var pdf=read>=5&&signature.Take(5).SequenceEqual("%PDF-"u8.ToArray());if(!jpeg&&!png&&!pdf)throw new ValidacionException("El contenido no corresponde a JPG, PNG o PDF válido.");var mime=pdf?"application/pdf":png?"image/png":"image/jpeg";var e=new EvidenciaFlujo{OrdenServicioLlantaId=x.Id,NombreArchivo=Path.GetFileName(archivo.FileName),MimeType=mime,TamanoBytes=archivo.Length,UsuarioCreacion=User.Username()};var root=Path.Combine(env.ContentRootPath,"App_Data","flujos");Directory.CreateDirectory(root);var path=Path.Combine(root,e.Id+ext);await using(var output=System.IO.File.Create(path))await source.CopyToAsync(output,ct);await using var input=System.IO.File.OpenRead(path);e.Hash=Convert.ToHexString(await SHA256.HashDataAsync(input,ct));e.Ubicacion=Path.Combine("App_Data","flujos",e.Id+ext);db.EvidenciasFlujo.Add(e);await db.SaveChangesAsync(ct);return Created(string.Empty,new{e.Id,e.NombreArchivo,e.Hash,e.MimeType,e.TamanoBytes});}
 [HttpGet("{id:guid}/evidencias")]public async Task<IReadOnlyList<EvidenciaDto>> Evidencias(Guid id,CancellationToken ct){await Orden(id,User.AlcanceCentros(),ct);return await db.EvidenciasFlujo.AsNoTracking().Where(x=>x.OrdenServicioLlantaId==id&&x.Activo).OrderByDescending(x=>x.FechaCreacion).Select(x=>new EvidenciaDto(x.Id,x.NombreArchivo,x.MimeType,x.TamanoBytes,x.Hash,x.FechaCreacion)).ToListAsync(ct);}
 [HttpGet("evidencias/{evidenciaId:guid}/descargar")]public async Task<IActionResult> Descargar(Guid evidenciaId,CancellationToken ct){var a=User.AlcanceCentros();var e=await db.EvidenciasFlujo.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==evidenciaId&&x.Activo&&(a.VerTodos||a.CentroIds.Contains(x.Orden.CentroOrigenId)||a.CentroIds.Contains(x.Orden.Llanta.CentroId)),ct);if(e is null)return NotFound();var root=Path.GetFullPath(Path.Combine(env.ContentRootPath,"App_Data","flujos"));var path=Path.GetFullPath(Path.Combine(env.ContentRootPath,e.Ubicacion));if(!path.StartsWith(root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)||!System.IO.File.Exists(path))return NotFound();return PhysicalFile(path,e.MimeType,e.NombreArchivo);}
 [HttpDelete("evidencias/{evidenciaId:guid}"),Authorize(Policy="ServiciosLlanta.Gestionar")]public async Task<IActionResult> Eliminar(Guid evidenciaId,CancellationToken ct){var a=User.AlcanceCentros();var e=await db.EvidenciasFlujo.SingleOrDefaultAsync(x=>x.Id==evidenciaId&&x.Activo&&(a.VerTodos||a.CentroIds.Contains(x.Orden.CentroOrigenId)||a.CentroIds.Contains(x.Orden.Llanta.CentroId)),ct);if(e is null)return NotFound();e.Activo=false;e.UsuarioModificacion=User.Username();await db.SaveChangesAsync(ct);return NoContent();}
 private async Task<OrdenServicioLlanta> Orden(Guid id,AlcanceCentros a,CancellationToken ct)=>await db.OrdenesServicioLlanta.Include(x=>x.Llanta).Include(x=>x.Evidencias).SingleOrDefaultAsync(x=>x.Id==id&&x.Activo&&(a.VerTodos||a.CentroIds.Contains(x.CentroOrigenId)||a.CentroIds.Contains(x.Llanta.CentroId)),ct)??throw new KeyNotFoundException("Orden no encontrada.");
 private async Task<OrdenDto> Dto(Guid id,AlcanceCentros a,CancellationToken ct)=>(await Listar(null,ct)).Single(x=>x.Id==id);
 public sealed record OrdenDto(Guid Id,string Tipo,string Estado,Guid LlantaId,string Llanta,Guid CentroId,string Centro,Guid? ProveedorId,string? Proveedor,decimal? Costo,string Motivo,string? Observaciones,bool Elegible,string? Criterio,DateTimeOffset? FechaEnvio,DateTimeOffset? FechaRecepcion,int Evidencias,string RowVersion);
 public sealed record EvidenciaDto(Guid Id,string NombreArchivo,string MimeType,long TamanoBytes,string Hash,DateTimeOffset Fecha);
 public sealed record ProveedorDto(Guid Id,string Codigo,string Nombre,string Tipo);public sealed record ProveedorInput(string Codigo,string Nombre,string Tipo);public sealed record CrearOrdenDto(string Tipo,Guid LlantaId,Guid? ProveedorId,decimal? Costo,string Motivo,string? Observaciones);public sealed record CerrarOrdenDto(bool Aceptada,string? Observaciones);
}
