import {Component,OnInit,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {firstValueFrom} from 'rxjs';
import {CatalogsApi} from '../../core/services/catalogs-api';
interface Rule{id?:string;codigo:string;nombre:string;tipo:string;descripcion:string;operador:string;valor:number;prioridad:string;centroId:string|null;activo:boolean;rowVersion?:string}
@Component({host:{class:'edinsa-workflow'},styleUrls:['../../shared/operational-workflow.scss'],selector:'app-alert-rules',imports:[FormsModule],template:`
<section><header class="workflow-header"><h2>Parametrización de alertas</h2><button (click)="create()">Crear regla</button></header><p>Se evalúan al guardar las lecturas de inspección. Los cambios no alteran alertas ni historiales anteriores.</p>@if(message()){<p class="message" [class.error]="messageKind()==='error'" role="status">{{message()}}</p>}
<div class="table"><table><thead><tr><th>Regla</th><th>Condición</th><th>Prioridad</th><th>Centro</th><th>Estado</th><th></th></tr></thead><tbody>@for(r of rules();track r.id){<tr><td>{{r.nombre}}<small>{{r.codigo}}</small></td><td>{{typeName(r.tipo)}} {{r.operador}} {{r.valor}} mm</td><td>{{r.prioridad}}</td><td>{{centerName(r.centroId)}}</td><td>{{r.activo?'Activa':'Inactiva'}}</td><td><button (click)="open(r,true)">Detalle</button><button (click)="open(r,false)">Editar</button><button [disabled]="saving()" (click)="toggle(r)">{{r.activo?'Desactivar':'Activar'}}</button></td></tr>}@empty{<tr><td colspan="6">No hay reglas configuradas.</td></tr>}</tbody></table></div>
@if(editor();as e){<div class="overlay"><section class="editor" role="dialog" aria-modal="true" aria-label="Regla de alerta"><header><h2>{{readOnly?'Detalle':e.id?'Editar regla':'Crear regla'}}</h2><button [disabled]="saving()" (click)="editor.set(null)">Cerrar</button></header>
<form (ngSubmit)="save()"><fieldset [disabled]="readOnly||saving()"><label>Código interno<input name="codigo" [(ngModel)]="e.codigo" [readonly]="!!e.id" required maxlength="80"></label><label>Nombre<input name="nombre" [(ngModel)]="e.nombre" required maxlength="150"></label><label>Tipo<select name="tipo" [(ngModel)]="e.tipo"><option value="DIFERENCIA_HOMBROS">Diferencia entre mediciones</option><option value="PROFUNDIDAD_MINIMA">Profundidad mínima</option></select></label><label>Descripción<textarea name="descripcion" [(ngModel)]="e.descripcion" maxlength="1000"></textarea></label>
<label>Operador<select name="operador" [(ngModel)]="e.operador">@for(op of operators;track op){<option [value]="op">{{op}}</option>}</select></label><label>Umbral (mm)<input type="number" name="valor" [(ngModel)]="e.valor" min="0" max="100" step="0.01" required></label><label>Prioridad<select name="prioridad" [(ngModel)]="e.prioridad"><option>Alta</option><option>Media</option><option>Baja</option></select></label><label>Centro<select name="centro" [(ngModel)]="e.centroId"><option [ngValue]="null">Todos los centros</option>@for(c of centers();track c.id){<option [value]="c.id">{{c.nombre}}</option>}</select></label><label><input type="checkbox" name="activo" [(ngModel)]="e.activo"> Activa</label></fieldset><p role="alert">{{message()}}</p>@if(!readOnly){<button class="primary" type="submit" [disabled]="saving()||!e.nombre.trim()||!e.codigo.trim()">Guardar regla</button>}</form></section></div>}
</section>`,styles:[`section{margin-top:1rem}header{display:flex;align-items:center;justify-content:space-between;gap:1rem}.table{overflow:auto;background:white}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.75rem;border-bottom:1px solid #dbe4e8}small{display:block;color:#647780}button,input,select,textarea{padding:.6rem;border:1px solid #cbd6dc;border-radius:7px}button{cursor:pointer;margin:.2rem}.primary{background:var(--edinsa-blue);color:white}.overlay{position:fixed;inset:0;background:#10202aaa;z-index:1000;display:grid;place-items:center;padding:1rem}.editor{background:white;padding:1.5rem;border-radius:14px;max-height:90vh;overflow:auto;width:min(620px,100%);box-sizing:border-box}fieldset{border:0;padding:0;display:grid;grid-template-columns:1fr 1fr;gap:.8rem}label{display:grid;gap:.4rem;min-width:0}input,select,textarea{min-width:0}button:disabled{opacity:.5}input[readonly]{background:#eef2f4}@media(max-width:600px){fieldset{grid-template-columns:1fr}}`]})
export class AlertRules implements OnInit{
 private http=inject(HttpClient);private catalogs=inject(CatalogsApi);rules=signal<Rule[]>([]);centers=signal<{id:string;nombre:string}[]>([]);editor=signal<Rule|null>(null);messageKind=signal('info');message=signal('');saving=signal(false);readOnly=false;operators=['>=','>','<=','<','=','!='];
 async ngOnInit(){try{this.centers.set(await firstValueFrom(this.catalogs.all('centros',true)));await this.load()}catch(e:any){this.messageKind.set('error');this.message.set(e?.userMessage??'No se pudo cargar la parametrización.')}}
 private async load(){this.rules.set(await firstValueFrom(this.http.get<Rule[]>('/api/alertas/parametros')))}
 create(){this.readOnly=false;this.message.set('');this.editor.set({codigo:'',nombre:'',tipo:'DIFERENCIA_HOMBROS',descripcion:'',operador:'>=',valor:3,prioridad:'Media',centroId:null,activo:true})}
 async open(rule:Rule,readOnly:boolean){try{this.editor.set(await firstValueFrom(this.http.get<Rule>(`/api/alertas/parametros/${rule.id}`)));this.readOnly=readOnly;this.message.set('')}catch(e:any){this.messageKind.set('error');this.message.set(e?.userMessage??'No se pudo abrir la regla.')}}
 async save(){const r=this.editor();if(!r||this.readOnly||this.saving())return;this.saving.set(true);try{await firstValueFrom(r.id?this.http.put(`/api/alertas/parametros/${r.id}`,r):this.http.post('/api/alertas/parametros',r));this.editor.set(null);await this.load();this.messageKind.set('success');this.message.set('Regla guardada. Se aplicará a las próximas lecturas.')}catch(e:any){this.messageKind.set('error');this.message.set(e?.userMessage??'No se pudo guardar. Revisa los campos o vuelve a abrir la regla.')}finally{this.saving.set(false)}}
 async toggle(r:Rule){this.saving.set(true);try{await firstValueFrom(this.http.patch(`/api/alertas/parametros/${r.id}/estado`,{activo:!r.activo,rowVersion:r.rowVersion}));await this.load()}catch(e:any){this.messageKind.set('error');this.message.set(e?.userMessage??'La regla cambió. Actualiza e intenta otra vez.')}finally{this.saving.set(false)}}
 centerName(id:string|null){return id?this.centers().find(c=>c.id===id)?.nombre??id:'Todos'}typeName(type:string){return type==='DIFERENCIA_HOMBROS'?'Diferencia':'Profundidad mínima'}
}
