import {Component,OnInit,inject,signal} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {firstValueFrom} from 'rxjs';
import {AuthService} from '../../core/auth/auth.service';
import {CatalogsApi} from '../../core/services/catalogs-api';
interface Request {id:string;fecha:string;tipo:string;solicitante:string;centro:string;vehiculo:string|null;llanta:string;serial:string;posicionOrigen:string|null;posicionDestino:string|null;kilometrajeVehiculo:number|null;motivo:string;observaciones:string|null;actividadProgramadaId:string|null;estado:string;aprobador:string|null;fechaDecision:string|null;motivoRechazo:string|null}
@Component({selector:'app-authorizations-page',imports:[CommonModule,FormsModule],template:`
<main><header><h1>Autorizaciones</h1><p>Revisa las solicitudes antes de ejecutar movimientos.</p></header>
<section class="filters"><label>Centro<select [(ngModel)]="filters.centroId"><option value="">Todos mis centros</option>@for(c of centers();track c.id){<option [value]="c.id">{{c.nombre}}</option>}</select></label>
<label>Operación<select [(ngModel)]="filters.tipo"><option value="">Todas</option>@for(t of types;track t){<option>{{t}}</option>}</select></label>
<label>Solicitante<input [(ngModel)]="filters.solicitante"></label><label>Vehículo / placa<input [(ngModel)]="filters.vehiculo"></label>
<label>Desde<input type="date" [(ngModel)]="filters.desde"></label><label>Hasta<input type="date" [(ngModel)]="filters.hasta"></label>
<label>Estado<select [(ngModel)]="filters.estado"><option>PENDIENTE_APROBACION</option><option>EJECUTADO</option><option>RECHAZADO</option><option value="TODOS">Todos</option></select></label><button [disabled]="loading()" (click)="page=1;load()">Consultar</button></section>
<p role="status">{{message()}}</p><p>{{total()}} solicitudes</p>
<div class="table"><table><thead><tr><th>Fecha</th><th>Operación</th><th>Solicitante / centro</th><th>Vehículo</th><th>Llanta / serial</th><th>Destino</th><th>Estado</th><th></th></tr></thead><tbody>@for(r of rows();track r.id){<tr><td>{{r.fecha|date:'short'}}</td><td>{{r.tipo}}</td><td>{{r.solicitante}}<small>{{r.centro}}</small></td><td>{{r.vehiculo||'—'}}</td><td>{{r.llanta}}<small>{{r.serial}}</small></td><td>{{r.posicionDestino||'—'}}</td><td>{{r.estado}}</td><td><button (click)="selected.set(r);rejection='';message.set('')">Revisar</button></td></tr>}@empty{<tr><td colspan="8">Sin solicitudes para estos filtros.</td></tr>}</tbody></table></div>
<nav><button [disabled]="page===1||loading()" (click)="page=page-1;load()">Anterior</button><span>Página {{page}}</span><button [disabled]="page*30>=total()||loading()" (click)="page=page+1;load()">Siguiente</button></nav>
@if(selected();as r){<div class="overlay"><section class="detail" role="dialog" aria-modal="true" aria-label="Detalle de solicitud"><header><h2>{{r.tipo}} · {{r.estado}}</h2><button [disabled]="saving()" (click)="selected.set(null)">Cerrar</button></header>
<dl><dt>Fecha / solicitante</dt><dd>{{r.fecha|date:'short'}} · {{r.solicitante}}</dd><dt>Centro / vehículo</dt><dd>{{r.centro}} · {{r.vehiculo||'—'}}</dd><dt>Llanta / serial</dt><dd>{{r.llanta}} · {{r.serial}}</dd><dt>Posición origen → destino</dt><dd>{{r.posicionOrigen||'Inventario'}} → {{r.posicionDestino||'Inventario / otro destino'}}</dd><dt>Kilometraje</dt><dd>{{r.kilometrajeVehiculo??'—'}}</dd><dt>Programación</dt><dd>{{r.actividadProgramadaId||'Sin programación'}}</dd><dt>Motivo</dt><dd>{{r.motivo}}</dd><dt>Observaciones</dt><dd>{{r.observaciones||'—'}}</dd>@if(r.aprobador){<dt>Decisión</dt><dd>{{r.aprobador}} · {{r.fechaDecision|date:'short'}} · {{r.motivoRechazo}}</dd>}</dl>
@if(r.estado==='PENDIENTE_APROBACION'){@if(r.solicitante===auth.user()?.username&&!auth.has('operaciones.aprobar_propia')){<p>No puedes resolver tu propia solicitud.</p>}@else{<label>Motivo de rechazo (obligatorio al rechazar)<textarea [(ngModel)]="rejection" maxlength="500"></textarea></label><footer><button [disabled]="saving()||!rejection.trim()" (click)="resolve(false)">Rechazar</button><button class="primary" [disabled]="saving()" (click)="resolve(true)">Aprobar y ejecutar</button></footer>}}<p role="alert">{{message()}}</p></section></div>}
</main>`,styles:[`main{display:grid;gap:1rem}.filters{display:flex;flex-wrap:wrap;gap:.8rem;align-items:end}label{display:grid;gap:.3rem}input,select,textarea,button{padding:.65rem;border:1px solid #ccd9df;border-radius:8px}button{cursor:pointer}button:disabled{opacity:.5;cursor:default}.primary{background:var(--edinsa-blue);color:white}.table{overflow:auto;background:white}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.75rem;border-bottom:1px solid #dde5ea}small{display:block;color:#536975}nav,header,footer{display:flex;gap:1rem;align-items:center;justify-content:space-between}.overlay{position:fixed;inset:0;background:#10202aaa;z-index:1000;display:grid;place-items:center;padding:1rem}.detail{background:white;border-radius:14px;padding:1.5rem;max-width:700px;width:100%;max-height:90vh;overflow:auto;box-sizing:border-box}dl{display:grid;grid-template-columns:1fr 2fr;gap:.6rem}dd{margin:0;overflow-wrap:anywhere}dt{font-weight:bold}textarea{width:100%;box-sizing:border-box}footer{margin-top:1rem}`]})
export class AuthorizationsPage implements OnInit{
 private http=inject(HttpClient);private catalogs=inject(CatalogsApi);readonly auth=inject(AuthService);
 rows=signal<Request[]>([]);centers=signal<{id:string;nombre:string}[]>([]);selected=signal<Request|null>(null);total=signal(0);loading=signal(false);saving=signal(false);message=signal('');page=1;rejection='';types=['Montaje','Desmontaje','Rotación','Traslado','Inventario','Reparación','Reencauche','Disposición final'];filters={centroId:'',tipo:'',solicitante:'',vehiculo:'',desde:'',hasta:'',estado:'PENDIENTE_APROBACION'};
 async ngOnInit(){try{this.centers.set(await firstValueFrom(this.catalogs.all('centros',true)))}catch{}await this.load()}
 async load(){this.loading.set(true);try{const params:Record<string,string>=Object.fromEntries(Object.entries(this.filters).filter(([,v])=>!!v));params['pagina']=String(this.page);const response=await firstValueFrom(this.http.get<{items:Request[];total:number}>('/api/operaciones/autorizaciones',{params}));this.rows.set(response.items);this.total.set(response.total)}catch(e:any){this.message.set(e?.userMessage??'No fue posible consultar las autorizaciones.')}finally{this.loading.set(false)}}
 async resolve(approve:boolean){const r=this.selected();if(!r||this.saving()||!approve&&!this.rejection.trim())return;this.saving.set(true);try{await firstValueFrom(this.http.post(`/api/operaciones/solicitudes/${r.id}/resolver`,{aprobar:approve,motivo:approve?null:this.rejection.trim()}));this.selected.set(null);this.message.set(approve?'Operación aprobada y ejecutada. Inventario actualizado.':'Solicitud rechazada. Inventario sin cambios.');await this.load()}catch(e:any){this.message.set(e?.userMessage??'No fue posible resolver: comprueba que llanta y posición sigan disponibles.')}finally{this.saving.set(false)}}
}
